use std::path::{Path, PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let proto_path = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?)
        .ancestors()
        .nth(2)
        .unwrap()
        .join("proto");

    tonic_build::configure()
        .build_server(true)
        .build_client(true)
        .compile_protos(
            &[
                proto_path
                    .join("mooncake_store_grpc.proto")
                    .to_str()
                    .unwrap(),
                proto_path
                    .join("mooncake_store_types.proto")
                    .to_str()
                    .unwrap(),
            ],
            &[proto_path],
        )?;

    if std::env::var_os("CARGO_FEATURE_SPDK_NOF_PROBE").is_some() {
        link_static_ibverbs_after_rdma_providers()?;
    }

    Ok(())
}

fn link_static_ibverbs_after_rdma_providers() -> Result<(), Box<dyn std::error::Error>> {
    // Ubuntu's static RDMA provider archives use private symbols exported by
    // libibverbs.a but not libibverbs.so. A link argument is emitted after the
    // provider libraries generated by spdk-rs so archive resolution succeeds.
    let output = std::process::Command::new("pkg-config")
        .args(["--variable=libdir", "libibverbs"])
        .output()?;
    if !output.status.success() {
        return Err("pkg-config could not find libibverbs".into());
    }
    let libdir = String::from_utf8(output.stdout)?;
    let archive = Path::new(libdir.trim()).join("libibverbs.a");
    if !archive.is_file() {
        return Err(format!(
            "static libibverbs archive not found at {}",
            archive.display()
        )
        .into());
    }
    println!("cargo:rustc-link-arg={}", archive.display());
    Ok(())
}
