//! Safe Rust bindings for the Mooncake Transfer Engine C API.
//!
//! This crate wraps the raw FFI generated by bindgen into idiomatic Rust types
//! with proper error handling and memory safety.

mod ffi {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::useless_transmute)]
    include!(concat!(env!("OUT_DIR"), "/transfer_engine_bindings.rs"));
}

mod error;
mod segment;
mod transfer;

pub use error::{TransferEngineError, TransferEngineResult};
pub use segment::{SegmentDesc, SegmentId};
pub use transfer::{
    BatchId, Opcode, TransferRequest, TransferStatus, TransferStatusEnum,
};

use std::ffi::{c_void, CStr, CString};
use std::ptr::NonNull;

// ---------------------------------------------------------------------------
// TransferEngine — owning handle
// ---------------------------------------------------------------------------

/// An initialized Transfer Engine instance.
///
/// Dropping this handle calls `destroyTransferEngine`.
#[derive(Debug)]
pub struct TransferEngine {
    handle: NonNull<c_void>,
}

unsafe impl Send for TransferEngine {}
unsafe impl Sync for TransferEngine {}

impl TransferEngine {
    /// Create a new Transfer Engine instance.
    ///
    /// `metadata_conn_string` — etcd/HTTP/P2PHANDSHAKE address for peer discovery.
    /// `local_server_name`   — `ip:port` or hostname of this node.
    /// `rpc_port`            — port for RPC communication.
    /// `auto_discover`       — whether to auto-discover NIC topology.
    pub fn create(
        metadata_conn_string: &str,
        local_server_name: &str,
        ip_or_host_name: &str,
        rpc_port: u64,
        auto_discover: bool,
    ) -> TransferEngineResult<Self> {
        let metadata_c = CString::new(metadata_conn_string)?;
        let server_c = CString::new(local_server_name)?;
        let ip_c = CString::new(ip_or_host_name)?;

        let handle = unsafe {
            ffi::createTransferEngine(
                metadata_c.as_ptr(),
                server_c.as_ptr(),
                ip_c.as_ptr(),
                rpc_port,
                auto_discover as i32,
            )
        };

        let handle = NonNull::new(handle).ok_or(TransferEngineError::NullHandle)?;
        Ok(Self { handle })
    }

    /// Install a transport protocol (e.g. `"tcp"` or `"rdma"`).
    ///
    /// For RDMA, `topology_matrix` is a semicolon-separated NIC priority string.
    pub fn install_transport(
        &self,
        protocol: &str,
        topology_matrix: Option<&str>,
    ) -> TransferEngineResult<()> {
        let proto_c = CString::new(protocol)?;
        let matrix_c = topology_matrix.map(CString::new).transpose()?;
        let matrix_ptr = matrix_c.as_ref().map_or(std::ptr::null(), |c| c.as_ptr());

        let mut args: [*const c_void; 2] = [
            matrix_ptr as *const c_void,
            std::ptr::null(),
        ];

        let xport = unsafe {
            ffi::installTransport(
                self.handle.as_ptr(),
                proto_c.as_ptr(),
                args.as_mut_ptr() as *mut *mut c_void,
            )
        };

        if xport.is_null() {
            return Err(TransferEngineError::InstallTransportFailed);
        }
        Ok(())
    }

    /// Discover NIC/GPU topology.
    pub fn discover_topology(&self) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::discoverTopology(self.handle.as_ptr()) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Get the local IP:port string this engine is listening on.
    pub fn get_local_ip_and_port(&self) -> TransferEngineResult<String> {
        let mut buf = vec![0u8; 256];
        let rc = unsafe {
            ffi::getLocalIpAndPort(self.handle.as_ptr(), buf.as_mut_ptr() as *mut i8, buf.len())
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        let cstr = CStr::from_bytes_until_nul(&buf)
            .map_err(|_| TransferEngineError::OperationFailed(-1))?;
        Ok(cstr.to_str()?.to_string())
    }

    // -----------------------------------------------------------------------
    // Memory registration
    // -----------------------------------------------------------------------

    /// Register a local memory region for remote access.
    ///
    /// `location` is a device identifier like `"cpu:0"` or `"cuda:0"`.
    /// `remote_accessible` — whether remote peers can read/write this region.
    ///
    /// # Safety
    /// `addr` must point to valid memory of at least `length` bytes.
    pub unsafe fn register_local_memory(
        &self,
        addr: *mut c_void,
        length: usize,
        location: &str,
        remote_accessible: bool,
    ) -> TransferEngineResult<()> {
        let loc_c = CString::new(location)?;
        let rc = unsafe {
            ffi::registerLocalMemory(
                self.handle.as_ptr(),
                addr,
                length,
                loc_c.as_ptr(),
                remote_accessible as i32,
            )
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Unregister a previously registered local memory region.
    ///
    /// # Safety
    /// `addr` must be the same pointer passed to `register_local_memory`.
    pub unsafe fn unregister_local_memory(&self, addr: *mut c_void) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::unregisterLocalMemory(self.handle.as_ptr(), addr) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    // -----------------------------------------------------------------------
    // Segment management
    // -----------------------------------------------------------------------

    /// Open a remote segment identified by `segment_name` (IP:port).
    pub fn open_segment(&self, segment_name: &str) -> TransferEngineResult<SegmentId> {
        let name_c = CString::new(segment_name)?;
        let id = unsafe { ffi::openSegment(self.handle.as_ptr(), name_c.as_ptr()) };
        if id < 0 {
            return Err(TransferEngineError::OperationFailed(id));
        }
        Ok(SegmentId(id))
    }

    /// Close a previously opened segment.
    pub fn close_segment(&self, segment_id: SegmentId) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::closeSegment(self.handle.as_ptr(), segment_id.0) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    // -----------------------------------------------------------------------
    // Transfer submission
    // -----------------------------------------------------------------------

    /// Allocate a batch ID for submitting a group of transfer requests.
    pub fn allocate_batch_id(&self, batch_size: usize) -> TransferEngineResult<BatchId> {
        let id = unsafe { ffi::allocateBatchID(self.handle.as_ptr(), batch_size) };
        if id == ffi::INVALID_BATCH as u64 {
            return Err(TransferEngineError::OperationFailed(-1));
        }
        Ok(BatchId(id))
    }

    /// Submit a batch of transfer requests.
    pub fn submit_transfer(
        &self,
        batch_id: BatchId,
        requests: &[TransferRequest],
    ) -> TransferEngineResult<()> {
        let mut ffi_requests: Vec<ffi::transfer_request_t> = requests
            .iter()
            .map(|r| ffi::transfer_request_t {
                opcode: r.opcode as i32,
                source: r.source,
                target_id: r.target_id.0,
                target_offset: r.target_offset,
                length: r.length,
            })
            .collect();

        let rc = unsafe {
            ffi::submitTransfer(
                self.handle.as_ptr(),
                batch_id.0,
                ffi_requests.as_mut_ptr(),
                ffi_requests.len(),
            )
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Poll the status of a single transfer within a batch.
    pub fn get_transfer_status(
        &self,
        batch_id: BatchId,
        task_id: usize,
    ) -> TransferEngineResult<TransferStatus> {
        let mut status = ffi::transfer_status_t {
            status: 0,
            transferred_bytes: 0,
        };
        let rc = unsafe {
            ffi::getTransferStatus(self.handle.as_ptr(), batch_id.0, task_id, &mut status)
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(TransferStatus {
            status: TransferStatusEnum::from_i32(status.status),
            transferred_bytes: status.transferred_bytes,
        })
    }

    /// Release a batch ID after all transfers complete.
    pub fn free_batch_id(&self, batch_id: BatchId) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::freeBatchID(self.handle.as_ptr(), batch_id.0) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }
}

impl Drop for TransferEngine {
    fn drop(&mut self) {
        unsafe {
            ffi::destroyTransferEngine(self.handle.as_ptr());
        }
    }
}
