//! Safe Rust bindings for the Mooncake Transfer Engine C API.
//!
//! This crate wraps the raw FFI generated by bindgen into idiomatic Rust types
//! with proper error handling and memory safety.

mod ffi {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::useless_transmute)]
    include!(concat!(env!("OUT_DIR"), "/transfer_engine_bindings.rs"));

    // INVALID_BATCH is defined as UINT64_MAX in transfer_engine_c.h;
    // bindgen cannot resolve it because it requires system headers.
    // Supply the constant ourselves so the ffi module stays self-contained.
    pub const INVALID_BATCH: u64 = u64::MAX;
}

mod error;
mod segment;
mod transfer;

pub use error::{TransferEngineError, TransferEngineResult};
pub use segment::{SegmentDesc, SegmentId};
pub use transfer::{
    BatchId, NotifyMsg, NotifyMsgBuf, Opcode, TransferRequest, TransferStatus, TransferStatusEnum,
};

use std::ffi::{c_void, CStr, CString};
use std::ptr::NonNull;

// ---------------------------------------------------------------------------
// TransferEngine — owning handle
// ---------------------------------------------------------------------------

/// An initialized Transfer Engine instance.
///
/// Dropping this handle calls `destroyTransferEngine`.
#[derive(Debug)]
pub struct TransferEngine {
    handle: NonNull<c_void>,
}

unsafe impl Send for TransferEngine {}
unsafe impl Sync for TransferEngine {}

impl TransferEngine {
    /// Create a new Transfer Engine instance.
    ///
    /// `metadata_conn_string` — etcd/HTTP/P2PHANDSHAKE address for peer discovery.
    /// `local_server_name`   — `ip:port` or hostname of this node.
    /// `rpc_port`            — port for RPC communication.
    /// `auto_discover`       — whether to auto-discover NIC topology.
    pub fn create(
        metadata_conn_string: &str,
        local_server_name: &str,
        ip_or_host_name: &str,
        rpc_port: u64,
        auto_discover: bool,
    ) -> TransferEngineResult<Self> {
        let metadata_c = CString::new(metadata_conn_string)?;
        let server_c = CString::new(local_server_name)?;
        let ip_c = CString::new(ip_or_host_name)?;

        let handle = unsafe {
            ffi::createTransferEngine(
                metadata_c.as_ptr(),
                server_c.as_ptr(),
                ip_c.as_ptr(),
                rpc_port,
                auto_discover as i32,
            )
        };

        let handle = NonNull::new(handle).ok_or(TransferEngineError::NullHandle)?;
        Ok(Self { handle })
    }

    /// Install a transport protocol (e.g. `"tcp"` or `"rdma"`).
    ///
    /// For RDMA, `topology_matrix` is a semicolon-separated NIC priority string.
    pub fn install_transport(
        &self,
        protocol: &str,
        topology_matrix: Option<&str>,
    ) -> TransferEngineResult<()> {
        let proto_c = CString::new(protocol)?;
        let matrix_c = topology_matrix.map(CString::new).transpose()?;
        let matrix_ptr = matrix_c.as_ref().map_or(std::ptr::null(), |c| c.as_ptr());

        let mut args: [*const c_void; 2] = [matrix_ptr as *const c_void, std::ptr::null()];

        let xport = unsafe {
            ffi::installTransport(
                self.handle.as_ptr(),
                proto_c.as_ptr(),
                args.as_mut_ptr() as *mut *mut c_void,
            )
        };

        if xport.is_null() {
            return Err(TransferEngineError::InstallTransportFailed);
        }
        Ok(())
    }

    /// Uninstall a previously installed transport protocol.
    pub fn uninstall_transport(&self, protocol: &str) -> TransferEngineResult<()> {
        let proto_c = CString::new(protocol)?;
        let rc = unsafe { ffi::uninstallTransport(self.handle.as_ptr(), proto_c.as_ptr()) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Discover NIC/GPU topology.
    pub fn discover_topology(&self) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::discoverTopology(self.handle.as_ptr()) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Get the local IP:port string this engine is listening on.
    pub fn get_local_ip_and_port(&self) -> TransferEngineResult<String> {
        let mut buf = vec![0u8; 256];
        let rc = unsafe {
            ffi::getLocalIpAndPort(self.handle.as_ptr(), buf.as_mut_ptr() as *mut i8, buf.len())
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        let cstr = CStr::from_bytes_until_nul(&buf)
            .map_err(|_| TransferEngineError::OperationFailed(-1))?;
        Ok(cstr.to_str()?.to_string())
    }

    // -----------------------------------------------------------------------
    // Memory registration
    // -----------------------------------------------------------------------

    /// Register a local memory region for remote access.
    ///
    /// `location` is a device identifier like `"cpu:0"` or `"cuda:0"`.
    /// `remote_accessible` — whether remote peers can read/write this region.
    ///
    /// # Safety
    /// `addr` must point to valid memory of at least `length` bytes.
    pub unsafe fn register_local_memory(
        &self,
        addr: *mut c_void,
        length: usize,
        location: &str,
        remote_accessible: bool,
    ) -> TransferEngineResult<()> {
        let loc_c = CString::new(location)?;
        let rc = unsafe {
            ffi::registerLocalMemory(
                self.handle.as_ptr(),
                addr,
                length,
                loc_c.as_ptr(),
                remote_accessible as i32,
            )
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Unregister a previously registered local memory region.
    ///
    /// # Safety
    /// `addr` must be the same pointer passed to `register_local_memory`.
    pub unsafe fn unregister_local_memory(&self, addr: *mut c_void) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::unregisterLocalMemory(self.handle.as_ptr(), addr) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Register multiple local memory regions in a single call.
    ///
    /// # Safety
    /// Each `(addr, length)` tuple must point to valid memory.
    pub unsafe fn register_local_memory_batch(
        &self,
        buffers: &[(usize, usize)],
        location: &str,
    ) -> TransferEngineResult<()> {
        let loc_c = CString::new(location)?;
        let mut entries: Vec<ffi::buffer_entry_t> = buffers
            .iter()
            .map(|(addr, len)| ffi::buffer_entry_t {
                addr: *addr as *mut c_void,
                length: *len,
            })
            .collect();
        let rc = unsafe {
            ffi::registerLocalMemoryBatch(
                self.handle.as_ptr(),
                entries.as_mut_ptr(),
                entries.len(),
                loc_c.as_ptr(),
            )
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Unregister multiple local memory regions in a single call.
    ///
    /// # Safety
    /// Each address must have been previously registered.
    pub unsafe fn unregister_local_memory_batch(
        &self,
        addrs: &[usize],
    ) -> TransferEngineResult<()> {
        let mut ptrs: Vec<*mut c_void> = addrs.iter().map(|a| *a as *mut c_void).collect();
        let rc = unsafe {
            ffi::unregisterLocalMemoryBatch(self.handle.as_ptr(), ptrs.as_mut_ptr(), ptrs.len())
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    // -----------------------------------------------------------------------
    // Segment management
    // -----------------------------------------------------------------------

    /// Open a remote segment identified by `segment_name` (IP:port).
    pub fn open_segment(&self, segment_name: &str) -> TransferEngineResult<SegmentId> {
        tracing::info!(target: "te_debug", %segment_name, "open_segment: calling C API");
        let name_c = CString::new(segment_name)?;
        let id = unsafe { ffi::openSegment(self.handle.as_ptr(), name_c.as_ptr()) };
        tracing::info!(target: "te_debug", %segment_name, seg_id = id, "open_segment: C API returned");
        if id < 0 {
            tracing::error!(target: "te_debug", %segment_name, seg_id = id, "open_segment: FAILED");
            return Err(TransferEngineError::OperationFailed(id));
        }
        Ok(SegmentId(id))
    }

    /// Close a previously opened segment.
    pub fn close_segment(&self, segment_id: SegmentId) -> TransferEngineResult<()> {
        tracing::info!(target: "te_debug", seg_id = segment_id.0, "close_segment: calling C API");
        let rc = unsafe { ffi::closeSegment(self.handle.as_ptr(), segment_id.0) };
        tracing::info!(target: "te_debug", seg_id = segment_id.0, rc, "close_segment: C API returned");
        if rc != 0 {
            tracing::error!(target: "te_debug", seg_id = segment_id.0, rc, "close_segment: FAILED");
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Open a remote segment without using the local cache.
    pub fn open_segment_no_cache(&self, segment_name: &str) -> TransferEngineResult<SegmentId> {
        let name_c = CString::new(segment_name)?;
        let id = unsafe { ffi::openSegmentNoCache(self.handle.as_ptr(), name_c.as_ptr()) };
        if id < 0 {
            return Err(TransferEngineError::OperationFailed(id));
        }
        Ok(SegmentId(id))
    }

    /// Eagerly pre-connect all EFA endpoints to the given segment.
    /// No-op on non-EFA installs. Returns `Ok(())` on success.
    pub fn warmup_efa_segment(&self, segment_name: &str) -> TransferEngineResult<()> {
        let name_c = CString::new(segment_name)?;
        let rc = unsafe { ffi::warmupEfaSegment(self.handle.as_ptr(), name_c.as_ptr()) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Remove a locally registered segment.
    pub fn remove_local_segment(&self, segment_name: &str) -> TransferEngineResult<()> {
        let name_c = CString::new(segment_name)?;
        let rc = unsafe { ffi::removeLocalSegment(self.handle.as_ptr(), name_c.as_ptr()) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Synchronize the segment cache.
    pub fn sync_segment_cache(&self) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::syncSegmentCache(self.handle.as_ptr()) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    // -----------------------------------------------------------------------
    // Transfer submission
    // -----------------------------------------------------------------------

    /// Allocate a batch ID for submitting a group of transfer requests.
    pub fn allocate_batch_id(&self, batch_size: usize) -> TransferEngineResult<BatchId> {
        tracing::info!(target: "te_debug", batch_size, "allocate_batch_id: calling C API");
        let id = unsafe { ffi::allocateBatchID(self.handle.as_ptr(), batch_size) };
        tracing::info!(target: "te_debug", batch_size, batch_id = id, "allocate_batch_id: C API returned");
        if id == ffi::INVALID_BATCH {
            tracing::error!(target: "te_debug", batch_size, "allocate_batch_id: INVALID_BATCH");
            return Err(TransferEngineError::OperationFailed(-1));
        }
        Ok(BatchId(id))
    }

    /// Submit a batch of transfer requests.
    pub fn submit_transfer(
        &self,
        batch_id: BatchId,
        requests: &[TransferRequest],
    ) -> TransferEngineResult<()> {
        tracing::info!(
            target: "te_debug",
            batch_id = batch_id.0,
            req_count = requests.len(),
            "submit_transfer: calling C API"
        );
        let mut ffi_requests: Vec<ffi::transfer_request_t> = requests
            .iter()
            .enumerate()
            .map(|(i, r)| {
                tracing::info!(
                    target: "te_debug",
                    batch_id = batch_id.0,
                    idx = i,
                    opcode = r.opcode as i32,
                    src = ?r.source,
                    tgt_id = r.target_id.0,
                    tgt_off = r.target_offset,
                    len = r.length,
                    "submit_transfer: request detail"
                );
                ffi::transfer_request_t {
                    opcode: r.opcode as i32,
                    source: r.source,
                    target_id: r.target_id.0,
                    target_offset: r.target_offset,
                    length: r.length,
                }
            })
            .collect();

        let rc = unsafe {
            ffi::submitTransfer(
                self.handle.as_ptr(),
                batch_id.0,
                ffi_requests.as_mut_ptr(),
                ffi_requests.len(),
            )
        };
        tracing::info!(target: "te_debug", batch_id = batch_id.0, rc, "submit_transfer: C API returned");
        if rc != 0 {
            tracing::error!(target: "te_debug", batch_id = batch_id.0, rc, "submit_transfer: FAILED");
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Poll the status of a single transfer within a batch.
    pub fn get_transfer_status(
        &self,
        batch_id: BatchId,
        task_id: usize,
    ) -> TransferEngineResult<TransferStatus> {
        let mut status = ffi::transfer_status_t {
            status: 0,
            transferred_bytes: 0,
        };
        let rc = unsafe {
            ffi::getTransferStatus(self.handle.as_ptr(), batch_id.0, task_id, &mut status)
        };
        if rc != 0 {
            tracing::error!(
                target: "te_debug",
                batch_id = batch_id.0,
                task_id,
                rc,
                "get_transfer_status: FAILED"
            );
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(TransferStatus {
            status: TransferStatusEnum::from_i32(status.status),
            transferred_bytes: status.transferred_bytes,
        })
    }

    /// Release a batch ID after all transfers complete.
    pub fn free_batch_id(&self, batch_id: BatchId) -> TransferEngineResult<()> {
        tracing::info!(target: "te_debug", batch_id = batch_id.0, "free_batch_id: calling C API");
        let rc = unsafe { ffi::freeBatchID(self.handle.as_ptr(), batch_id.0) };
        tracing::info!(target: "te_debug", batch_id = batch_id.0, rc, "free_batch_id: C API returned");
        if rc != 0 {
            tracing::error!(target: "te_debug", batch_id = batch_id.0, rc, "free_batch_id: FAILED");
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    // -----------------------------------------------------------------------
    // Transfer with notification
    // -----------------------------------------------------------------------

    /// Submit a batch of transfer requests and send a notification on completion.
    pub fn submit_transfer_with_notify(
        &self,
        batch_id: BatchId,
        requests: &[TransferRequest],
        notify_msg: &NotifyMsg,
    ) -> TransferEngineResult<()> {
        let mut ffi_requests: Vec<ffi::transfer_request_t> = requests
            .iter()
            .map(|r| ffi::transfer_request_t {
                opcode: r.opcode as i32,
                source: r.source,
                target_id: r.target_id.0,
                target_offset: r.target_offset,
                length: r.length,
            })
            .collect();

        let name_c = CString::new(notify_msg.name.as_str())?;
        let msg_c = CString::new(notify_msg.msg.as_str())?;
        let ffi_notify = ffi::notify_msg_t {
            name: name_c.as_ptr() as *mut i8,
            msg: msg_c.as_ptr() as *mut i8,
        };

        let rc = unsafe {
            ffi::submitTransferWithNotify(
                self.handle.as_ptr(),
                batch_id.0,
                ffi_requests.as_mut_ptr(),
                ffi_requests.len(),
                ffi_notify,
            )
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Generate a notification message and send it to a target peer.
    pub fn gen_notify_in_engine(
        &self,
        target_id: u64,
        notify_msg: &NotifyMsg,
    ) -> TransferEngineResult<()> {
        let name_c = CString::new(notify_msg.name.as_str())?;
        let msg_c = CString::new(notify_msg.msg.as_str())?;
        let ffi_notify = ffi::notify_msg_t {
            name: name_c.as_ptr() as *mut i8,
            msg: msg_c.as_ptr() as *mut i8,
        };
        let rc = unsafe { ffi::genNotifyInEngine(self.handle.as_ptr(), target_id, ffi_notify) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Poll for incoming notification messages.
    pub fn get_notifs_from_engine(&self) -> TransferEngineResult<Vec<NotifyMsg>> {
        let mut size: i32 = 0;
        let raw = unsafe { ffi::getNotifsFromEngine(self.handle.as_ptr(), &mut size) };
        if raw.is_null() && size > 0 {
            return Err(TransferEngineError::OperationFailed(-1));
        }
        let count = size as usize;
        let mut out = Vec::with_capacity(count);
        for i in 0..count {
            let entry = unsafe { &*raw.add(i) };
            let name = unsafe { CStr::from_ptr(entry.name) }.to_str()?.to_string();
            let msg = unsafe { CStr::from_ptr(entry.msg) }.to_str()?.to_string();
            out.push(NotifyMsg { name, msg });
        }
        if count > 0 {
            unsafe { ffi::freeNotifsMsgBuf(raw, size) };
        }
        Ok(out)
    }
}

impl Drop for TransferEngine {
    fn drop(&mut self) {
        unsafe {
            ffi::destroyTransferEngine(self.handle.as_ptr());
        }
    }
}
