//! Safe Rust bindings for the Mooncake Transfer Engine C API.
//!
//! # FFI Layer Overview / FFI 层概述
//!
//! This library provides a safe Rust wrapper around the Mooncake C++ Transfer Engine.
//! The C++ engine is a high-performance data transfer runtime that supports RDMA,
//! TCP, and NVMe-oF transports. Rust code interacts with it exclusively through
//! the C ABI (FFI) generated by `bindgen`.
//!
//! 本 Rust 包为 Mooncake C++ Transfer Engine 提供安全的 Rust 封装。C++ 引擎是一个
//! 高性能数据传输运行时，支持 RDMA、TCP 和 NVMe-oF 传输协议。Rust 代码通过 bindgen
//! 生成的 C ABI (FFI) 与 C++ 引擎交互。
//!
//! ## Architecture / 架构
//!
//! ```text
//! Rust code ──► TransferEngine (safe handle) ──► FFI bindings ──► C++ TransferEngine
//!      │                    │
//!      │ owns              │ wraps raw *mut c_void
//!      │ the pointer       │ with NonNull
//!      │                   │
//!  Drop calls          createTransferEngine()
//!  destroyTransferEngine()  ...
//! ```
//!
//! ## Lifecycle / 生命周期
//!
//! The standard lifecycle of a Transfer Engine session is:
//! 标准的 Transfer Engine 会话生命周期如下：
//!
//! 1. **create** — 创建引擎实例，连接到元数据服务（etcd/HTTP/P2PHANDSHAKE）
//! 2. **install_transport** — 安装传输协议（TCP 或 RDMA），配置网卡优先级
//! 3. **discover_topology** — 发现 NIC/GPU 拓扑结构
//! 4. **register_local_memory** — 注册本地内存区域，使其可被远程节点访问
//! 5. **open_segment** — 打开远程节点的内存段，获取 SegmentId
//! 6. **allocate_batch_id → submit_transfer → get_transfer_status → free_batch_id**
//!    — 提交批量传输请求，轮询状态，完成后释放批次
//! 7. **close_segment** — 关闭已打开的远程段
//! 8. **unregister_local_memory** — 注销本地内存
//! 9. **Drop (destroy)** — 销毁引擎实例，释放所有资源
//!
//! ## Key Design Decisions / 关键设计决策
//!
//! - **Ownership**: `TransferEngine` owns the raw C pointer; `Drop` calls
//!   `destroyTransferEngine` to prevent leaks.
//! - **NonNull**: The internal handle is `NonNull<c_void>`, guaranteeing the
//!   pointer is never null after successful creation.
//! - **Send + Sync**: The engine is thread-safe by design; the raw C++ layer
//!   uses internal locking.
//! - **Error mapping**: All C return codes are mapped to `TransferEngineError`
//!   variants for idiomatic Rust error handling.
//!
//! - **所有权**: `TransferEngine` 拥有原始 C 指针的所有权；`Drop` 时调用
//!   `destroyTransferEngine` 防止资源泄漏。
//! - **NonNull**: 内部句柄使用 `NonNull<c_void>`，保证创建成功后指针永不为空。
//! - **Send + Sync**: 引擎设计为线程安全；C++ 底层使用内部锁机制。
//! - **错误映射**: 所有 C 返回码映射为 `TransferEngineError` 变体，
//!   提供符合 Rust 习惯的错误处理。

mod ffi {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::useless_transmute)]

    // Include the bindgen-generated FFI bindings for the C++ Transfer Engine.
    // 包含由 bindgen 生成的 C++ Transfer Engine 的 FFI 绑定。
    include!(concat!(env!("OUT_DIR"), "/transfer_engine_bindings.rs"));
}

mod accelerator;
mod error;
mod nic_stats;
mod registered_memory;
mod segment;
mod tent;
mod transfer;
mod transport_hint;

pub use accelerator::{PointerMemoryType, classify_pointer, copy_from_host, copy_to_host};
pub use error::{TransferEngineError, TransferEngineResult};
pub use nic_stats::NicLoadStats;
pub use registered_memory::{
    ReadableRegisteredMemoryRegion, RegisteredMemory, RegisteredMemoryAccess, RegisteredMemoryId,
    RegisteredSubmitOutcome, RegisteredTransferRequest, StableMemoryOwner,
    SubmittedRegisteredBatch, WritableRegisteredMemoryRegion,
};
pub use segment::{SegmentDesc, SegmentId};
pub use tent::{
    TentEngine, TentIntent, TentMetricsStatus, TentPriority, TentRequestOptions,
    TentTransferRequest, TentTransport,
};
pub use transfer::{
    BatchId, NotifyMsg, NotifyMsgBuf, Opcode, OwnedBatchId, TransferRequest, TransferStatus,
    TransferStatusEnum,
};
pub use transport_hint::{HintedTransferRequest, TransportHint};

use std::ffi::{CStr, CString, c_void};
use std::ptr::NonNull;
use std::sync::Mutex;
use std::sync::atomic::AtomicU64;
use transfer::next_engine_instance_id;

// ---------------------------------------------------------------------------
// TransferEngine — owning handle
// TransferEngine — 拥有所有权的句柄
// ---------------------------------------------------------------------------

/// An initialized Transfer Engine instance.
/// 一个已初始化的 Transfer Engine 实例。
///
/// This struct wraps a raw C pointer to the underlying C++ TransferEngine.
/// It is the primary entry point for all transfer operations.
/// 该结构体封装了指向底层 C++ TransferEngine 的原始 C 指针。
/// 它是所有传输操作的主要入口点。
///
/// # Safety / 安全性
///
/// The raw handle is stored as `NonNull<c_void>`, guaranteeing it is
/// never null after construction. The engine is `Send + Sync` because
/// the C++ layer uses internal synchronization.
/// 原始句柄存储为 `NonNull<c_void>`，确保构造后永不为空。
/// 引擎实现了 `Send + Sync`，因为 C++ 层使用内部同步机制。
///
/// # Resource Management / 资源管理
///
/// Dropping this handle calls `destroyTransferEngine`, which frees all
/// associated C++ resources including registered memory regions, open
/// segments, and transport connections.
/// 丢弃此句柄时会调用 `destroyTransferEngine`，释放所有关联的 C++ 资源，
/// 包括已注册的内存区域、打开的段和传输连接。
#[derive(Debug)]
pub struct TransferEngine {
    handle: NonNull<c_void>,
    instance_id: u64,
    memory_registrations: Mutex<registered_memory::RegistrationRegistry>,
    next_memory_registration_generation: AtomicU64,
}

struct NativeNotifyBuffer {
    raw: *mut ffi::notify_msg_t,
    count: i32,
}

impl Drop for NativeNotifyBuffer {
    fn drop(&mut self) {
        if !self.raw.is_null() {
            unsafe {
                ffi::freeNotifsMsgBuf(self.raw, self.count.max(0));
            }
        }
    }
}

// SAFETY: The C++ TransferEngine uses internal locking for thread safety.
// The Rust wrapper only passes the opaque pointer through FFI calls,
// which are all guarded by the C++ layer's mutexes.
// 安全性：C++ TransferEngine 使用内部锁保证线程安全。
// Rust 封装仅通过 FFI 调用传递不透明指针，所有操作受 C++ 层互斥锁保护。
unsafe impl Send for TransferEngine {}
unsafe impl Sync for TransferEngine {}

impl TransferEngine {
    /// Create a new Transfer Engine instance.
    /// 创建一个新的 Transfer Engine 实例。
    ///
    /// This is the first step in the Transfer Engine lifecycle. It connects
    /// to the metadata service for peer discovery and initializes internal
    /// data structures.
    /// 这是 Transfer Engine 生命周期的第一步。它连接到元数据服务以进行
    /// 节点发现，并初始化内部数据结构。
    ///
    /// # Parameters / 参数
    ///
    /// - `metadata_conn_string` — etcd/HTTP/P2PHANDSHAKE address for peer discovery.
    ///   etcd/HTTP/P2PHANDSHAKE 地址，用于节点发现。
    /// - `local_server_name` — `ip:port` or hostname of this node.
    ///   本节点的 `ip:port` 或主机名。
    /// - `ip_or_host_name` — the IP address or hostname to bind.
    ///   要绑定的 IP 地址或主机名。
    /// - `rpc_port` — port for RPC communication between nodes.
    ///   用于节点间 RPC 通信的端口。
    /// - `auto_discover` — whether to auto-discover NIC topology on creation.
    ///   是否在创建时自动发现网卡拓扑。
    pub fn create(
        metadata_conn_string: &str,
        local_server_name: &str,
        ip_or_host_name: &str,
        rpc_port: u64,
        auto_discover: bool,
    ) -> TransferEngineResult<Self> {
        let metadata_c = CString::new(metadata_conn_string)?;
        let server_c = CString::new(local_server_name)?;
        let ip_c = CString::new(ip_or_host_name)?;

        let handle = unsafe {
            ffi::createTransferEngine(
                metadata_c.as_ptr(),
                server_c.as_ptr(),
                ip_c.as_ptr(),
                rpc_port,
                auto_discover as i32,
            )
        };

        let handle = NonNull::new(handle).ok_or(TransferEngineError::NullHandle)?;
        Ok(Self {
            handle,
            instance_id: next_engine_instance_id(),
            memory_registrations: Mutex::new(registered_memory::RegistrationRegistry::new()),
            next_memory_registration_generation: AtomicU64::new(1),
        })
    }

    /// Install a transport protocol (e.g. `"tcp"` or `"rdma"`).
    /// 安装传输协议（例如 `"tcp"` 或 `"rdma"`）。
    ///
    /// This must be called after `create` and before any transfer operations.
    /// The transport protocol determines how data is moved between nodes.
    /// 必须在 `create` 之后、任何传输操作之前调用。
    /// 传输协议决定节点间数据如何移动。
    ///
    /// # Parameters / 参数
    ///
    /// - `protocol` — transport protocol name: `"tcp"`, `"rdma"`, etc.
    ///   传输协议名称：`"tcp"`、`"rdma"` 等。
    /// - `topology_matrix` — semicolon-separated NIC priority string for RDMA
    ///   (e.g., `"mlx5_0,mlx5_1;mlx5_2"`). Each segment before a semicolon
    ///   represents one priority level. `None` for TCP.
    ///   分号分隔的网卡优先级字符串，用于 RDMA（如 `"mlx5_0,mlx5_1;mlx5_2"`）。
    ///   每个分号前的段表示一个优先级级别。TCP 时传 `None`。
    pub fn install_transport(
        &self,
        protocol: &str,
        topology_matrix: Option<&str>,
    ) -> TransferEngineResult<()> {
        let proto_c = CString::new(protocol)?;
        let matrix_c = topology_matrix.map(CString::new).transpose()?;
        let matrix_ptr = matrix_c.as_ref().map_or(std::ptr::null(), |c| c.as_ptr());

        let mut args: [*const c_void; 2] = [matrix_ptr as *const c_void, std::ptr::null()];

        let xport = unsafe {
            ffi::installTransport(
                self.handle.as_ptr(),
                proto_c.as_ptr(),
                args.as_mut_ptr() as *mut *mut c_void,
            )
        };

        if xport.is_null() {
            return Err(TransferEngineError::InstallTransportFailed);
        }
        Ok(())
    }

    /// Return the current per-NIC scheduler load observed by the native engine.
    pub fn nic_load_stats(&self) -> TransferEngineResult<Vec<NicLoadStats>> {
        nic_stats::query_nic_load_stats(
            "getNicLoadStats",
            |stats, count| unsafe { ffi::getNicLoadStats(self.handle.as_ptr(), stats, count) },
            nic_stats::decode_classic,
        )
    }

    /// Uninstall a previously installed transport protocol.
    /// 卸载之前安装的传输协议。
    ///
    /// Frees resources associated with the transport (connections, buffers, etc.).
    /// 释放与传输相关的资源（连接、缓冲区等）。
    pub fn uninstall_transport(&self, protocol: &str) -> TransferEngineResult<()> {
        let proto_c = CString::new(protocol)?;
        let rc = unsafe { ffi::uninstallTransport(self.handle.as_ptr(), proto_c.as_ptr()) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Discover NIC/GPU topology.
    /// 发现 NIC/GPU 拓扑结构。
    ///
    /// Scans the local machine for available RDMA NICs and GPUs, and builds
    /// a topology map used for optimizing transfer paths (e.g., GPU-Direct-RDMA).
    /// 扫描本地机器的可用 RDMA 网卡和 GPU，构建拓扑映射，
    /// 用于优化传输路径（如 GPU-Direct-RDMA）。
    pub fn discover_topology(&self) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::discoverTopology(self.handle.as_ptr()) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Get the local IP:port string this engine is listening on.
    /// 获取本引擎监听的本地 IP:port 字符串。
    ///
    /// This is useful after auto-discovery to determine the actual bound address.
    /// 在自动发现后可用于确定实际绑定的地址。
    pub fn get_local_ip_and_port(&self) -> TransferEngineResult<String> {
        let mut buf = vec![0u8; 256];
        let rc = unsafe {
            ffi::getLocalIpAndPort(
                self.handle.as_ptr(),
                buf.as_mut_ptr() as *mut std::os::raw::c_char,
                buf.len(),
            )
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        let cstr = CStr::from_bytes_until_nul(&buf)
            .map_err(|_| TransferEngineError::OperationFailed(-1))?;
        Ok(cstr.to_str()?.to_string())
    }

    /// Get the RPC port used by this engine.
    /// 获取当前引擎使用的 RPC 端口。
    pub fn get_rpc_port(&self) -> i32 {
        unsafe { ffi::getRpcPort(self.handle.as_ptr()) }
    }

    // -----------------------------------------------------------------------
    // Memory registration / 内存注册
    // -----------------------------------------------------------------------
    // Memory registration tells the transport layer which local memory regions
    // can be accessed by remote peers for RDMA read/write operations.
    // 内存注册告知传输层哪些本地内存区域可被远程节点通过 RDMA 读/写访问。

    /// Register a local memory region for remote access.
    /// 注册本地内存区域以供远程访问。
    ///
    /// Once registered, remote peers can read from or write to this memory
    /// region via RDMA, depending on the transport and permissions.
    /// 注册后，远程节点可以通过 RDMA 读取或写入此内存区域，
    /// 具体取决于传输协议和权限设置。
    ///
    /// # Parameters / 参数
    ///
    /// - `addr` — starting address of the memory region.
    ///   内存区域的起始地址。
    /// - `length` — size of the memory region in bytes.
    ///   内存区域的大小（字节）。
    /// - `location` — device identifier like `"cpu:0"` or `"cuda:0"`.
    ///   设备标识符，如 `"cpu:0"` 或 `"cuda:0"`。
    /// - `remote_accessible` — whether remote peers can read/write this region.
    ///   是否允许远程节点读写此区域。
    ///
    /// # Safety
    ///
    /// 安全性：
    ///
    /// `addr` must point to valid memory of at least `length` bytes.
    /// The memory must remain valid until `unregister_local_memory` is called.
    /// `addr` 必须指向至少 `length` 字节的有效内存。
    /// 内存在调用 `unregister_local_memory` 之前必须保持有效。
    pub unsafe fn register_local_memory(
        &self,
        addr: *mut c_void,
        length: usize,
        location: &str,
        remote_accessible: bool,
    ) -> TransferEngineResult<()> {
        let loc_c = CString::new(location)?;
        let rc = unsafe {
            ffi::registerLocalMemory(
                self.handle.as_ptr(),
                addr,
                length,
                loc_c.as_ptr(),
                remote_accessible as i32,
            )
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Unregister a previously registered local memory region.
    /// 注销之前注册的本地内存区域。
    ///
    /// After this call, remote peers can no longer access this memory.
    /// 调用后，远程节点无法再访问此内存。
    ///
    /// # Safety
    ///
    /// 安全性：
    ///
    /// `addr` must be the same pointer passed to `register_local_memory`.
    /// `addr` 必须与 `register_local_memory` 传入的指针相同。
    pub unsafe fn unregister_local_memory(&self, addr: *mut c_void) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::unregisterLocalMemory(self.handle.as_ptr(), addr) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Register multiple local memory regions in a single call.
    /// 在单次调用中注册多个本地内存区域。
    ///
    /// More efficient than calling `register_local_memory` repeatedly,
    /// as it reduces FFI overhead.
    /// 比反复调用 `register_local_memory` 更高效，减少了 FFI 开销。
    ///
    /// # Safety
    ///
    /// 安全性：
    ///
    /// Each `(addr, length)` tuple must point to valid memory.
    /// 每个 `(addr, length)` 元组必须指向有效内存。
    pub unsafe fn register_local_memory_batch(
        &self,
        buffers: &[(usize, usize)],
        location: &str,
    ) -> TransferEngineResult<()> {
        let loc_c = CString::new(location)?;
        let mut entries: Vec<ffi::buffer_entry_t> = buffers
            .iter()
            .map(|(addr, len)| ffi::buffer_entry_t {
                addr: *addr as *mut c_void,
                length: *len,
            })
            .collect();
        let rc = unsafe {
            ffi::registerLocalMemoryBatch(
                self.handle.as_ptr(),
                entries.as_mut_ptr(),
                entries.len(),
                loc_c.as_ptr(),
            )
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Unregister multiple local memory regions in a single call.
    /// 在单次调用中注销多个本地内存区域。
    ///
    /// # Safety
    ///
    /// 安全性：
    ///
    /// Each address must have been previously registered.
    /// 每个地址必须之前已经注册过。
    pub unsafe fn unregister_local_memory_batch(
        &self,
        addrs: &[usize],
    ) -> TransferEngineResult<()> {
        let mut ptrs: Vec<*mut c_void> = addrs.iter().map(|a| *a as *mut c_void).collect();
        let rc = unsafe {
            ffi::unregisterLocalMemoryBatch(self.handle.as_ptr(), ptrs.as_mut_ptr(), ptrs.len())
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    // -----------------------------------------------------------------------
    // Segment management / 段管理
    // -----------------------------------------------------------------------
    // A "segment" represents a remote memory region that has been advertised
    // via the metadata service. Opening a segment establishes the connection
    // and returns a SegmentId used in transfer requests.
    // "段" (segment) 表示通过元数据服务发布的远程内存区域。
    // 打开一个段会建立连接并返回在传输请求中使用的 SegmentId。

    /// Open a remote segment identified by `segment_name` (typically `IP:port`).
    /// 打开由 `segment_name`（通常为 `IP:port`）标识的远程段。
    ///
    /// Uses a local cache for segment handles. If a segment has been opened
    /// previously, the cached handle is returned. This is the preferred method
    /// for most use cases.
    /// 使用本地缓存获取段句柄。如果之前已打开过该段，则返回缓存的句柄。
    /// 这是大多数场景下的推荐方法。
    pub fn open_segment(&self, segment_name: &str) -> TransferEngineResult<SegmentId> {
        tracing::info!(target: "te_debug", %segment_name, "open_segment: calling C API");
        let name_c = CString::new(segment_name)?;
        let id = unsafe { ffi::openSegment(self.handle.as_ptr(), name_c.as_ptr()) };
        tracing::info!(target: "te_debug", %segment_name, seg_id = id, "open_segment: C API returned");
        if id < 0 {
            tracing::error!(target: "te_debug", %segment_name, seg_id = id, "open_segment: FAILED");
            return Err(TransferEngineError::OperationFailed(id));
        }
        Ok(SegmentId(id))
    }

    /// Close a previously opened segment.
    /// 关闭之前打开的段。
    ///
    /// Releases the connection resources associated with this segment.
    /// 释放与此段关联的连接资源。
    pub fn close_segment(&self, segment_id: SegmentId) -> TransferEngineResult<()> {
        tracing::info!(target: "te_debug", seg_id = segment_id.0, "close_segment: calling C API");
        let rc = unsafe { ffi::closeSegment(self.handle.as_ptr(), segment_id.0) };
        tracing::info!(target: "te_debug", seg_id = segment_id.0, rc, "close_segment: C API returned");
        if rc != 0 {
            tracing::error!(target: "te_debug", seg_id = segment_id.0, rc, "close_segment: FAILED");
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Check whether an opened segment is still valid/reachable.
    /// 检查已打开 segment 是否仍然有效/可达。
    pub fn check_segment_status(&self, segment_id: SegmentId) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::checkSegmentStatus(self.handle.as_ptr(), segment_id.0) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Open a remote segment without using the local cache.
    /// 打开远程段，但不使用本地缓存。
    ///
    /// Always creates a fresh connection, bypassing the segment handle cache.
    /// Useful when cache invalidation is needed.
    /// 总是创建新的连接，绕过段句柄缓存。
    /// 在需要缓存失效时使用。
    pub fn open_segment_no_cache(&self, segment_name: &str) -> TransferEngineResult<SegmentId> {
        let name_c = CString::new(segment_name)?;
        let id = unsafe { ffi::openSegmentNoCache(self.handle.as_ptr(), name_c.as_ptr()) };
        if id < 0 {
            return Err(TransferEngineError::OperationFailed(id));
        }
        Ok(SegmentId(id))
    }

    /// Eagerly pre-connect all EFA endpoints to the given segment.
    /// 主动预连接所有 EFA 端点到给定段。
    ///
    /// EFA (Elastic Fabric Adapter) is AWS's high-performance networking
    /// interface. This warmup avoids cold-start latency on the first transfer.
    /// No-op on non-EFA installs.
    /// EFA (Elastic Fabric Adapter) 是 AWS 的高性能网络接口。
    /// 此预热操作避免了首次传输的冷启动延迟。
    /// 在非 EFA 安装上为无操作。
    pub fn warmup_efa_segment(&self, segment_name: &str) -> TransferEngineResult<()> {
        let name_c = CString::new(segment_name)?;
        let rc = unsafe { ffi::warmupEfaSegment(self.handle.as_ptr(), name_c.as_ptr()) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Remove a locally registered segment.
    /// 移除本地注册的段。
    ///
    /// This unregisters a segment that was previously advertised to other nodes
    /// via the metadata service.
    /// 注销之前通过元数据服务向其他节点发布的段。
    pub fn remove_local_segment(&self, segment_name: &str) -> TransferEngineResult<()> {
        let name_c = CString::new(segment_name)?;
        let rc = unsafe { ffi::removeLocalSegment(self.handle.as_ptr(), name_c.as_ptr()) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Synchronize the segment cache.
    /// 同步段缓存。
    ///
    /// Refreshes the local segment cache from the metadata service, picking up
    /// any segments registered or removed by other nodes.
    /// 从元数据服务刷新本地段缓存，获取其他节点注册或移除的段。
    pub fn sync_segment_cache(&self) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::syncSegmentCache(self.handle.as_ptr()) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    // -----------------------------------------------------------------------
    // Transfer submission / 传输提交
    // -----------------------------------------------------------------------
    // The transfer workflow uses a batch abstraction:
    // 1. allocate_batch_id — reserve a batch slot for N requests
    // 2. submit_transfer — enqueue read/write requests into the batch
    // 3. get_transfer_status — poll each request until terminal
    // 4. free_batch_id — release the batch slot
    //
    // 传输工作流使用批次抽象：
    // 1. allocate_batch_id — 为 N 个请求预留批次槽位
    // 2. submit_transfer — 将读写请求入队到批次中
    // 3. get_transfer_status — 轮询每个请求直到终态
    // 4. free_batch_id — 释放批次槽位

    /// Allocate a legacy copyable batch token.
    ///
    /// This API is retained only for callers outside the Rust Store
    /// replacement. Store code must use [`Self::allocate_owned_batch_id`].
    pub fn allocate_batch_id(&self, batch_size: usize) -> TransferEngineResult<BatchId> {
        let id = unsafe { ffi::allocateBatchID(self.handle.as_ptr(), batch_size) };
        if id == u64::MAX {
            return Err(TransferEngineError::OperationFailed(-1));
        }
        Ok(BatchId(id))
    }

    /// Submit requests through the legacy copyable batch-token API.
    ///
    /// This preserves the pre-existing interface for out-of-scope consumers.
    /// It cannot express payload lifetime or aliasing in the type system; Rust
    /// Store callers must use the owned API through their safe adapter.
    pub fn submit_transfer(
        &self,
        batch_id: BatchId,
        requests: &[TransferRequest],
    ) -> TransferEngineResult<()> {
        let mut ffi_requests = requests
            .iter()
            .map(|request| ffi::transfer_request_t {
                opcode: request.opcode as i32,
                source: request.source,
                target_id: request.target_id.0,
                target_offset: request.target_offset,
                length: request.length,
            })
            .collect::<Vec<_>>();
        let rc = unsafe {
            ffi::submitTransfer(
                self.handle.as_ptr(),
                batch_id.0,
                ffi_requests.as_mut_ptr(),
                ffi_requests.len(),
            )
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Poll one task through the legacy copyable batch-token API.
    pub fn get_transfer_status(
        &self,
        batch_id: BatchId,
        task_id: usize,
    ) -> TransferEngineResult<TransferStatus> {
        let mut status = ffi::transfer_status_t {
            status: 0,
            transferred_bytes: 0,
        };
        let rc = unsafe {
            ffi::getTransferStatus(self.handle.as_ptr(), batch_id.0, task_id, &mut status)
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(TransferStatus {
            status: TransferStatusEnum::from_i32(status.status),
            transferred_bytes: status.transferred_bytes,
        })
    }

    /// Poll aggregate status through the legacy copyable batch-token API.
    pub fn get_batch_transfer_status(
        &self,
        batch_id: BatchId,
    ) -> TransferEngineResult<TransferStatus> {
        let mut status = ffi::transfer_status_t {
            status: 0,
            transferred_bytes: 0,
        };
        let rc =
            unsafe { ffi::getBatchTransferStatus(self.handle.as_ptr(), batch_id.0, &mut status) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(TransferStatus {
            status: TransferStatusEnum::from_i32(status.status),
            transferred_bytes: status.transferred_bytes,
        })
    }

    /// Release a legacy copyable batch token.
    pub fn free_batch_id(&self, batch_id: BatchId) -> TransferEngineResult<()> {
        let rc = unsafe { ffi::freeBatchID(self.handle.as_ptr(), batch_id.0) };
        if matches!(rc, 4 | -4) {
            return Err(TransferEngineError::BatchBusy);
        }
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Allocate a batch ID for submitting a group of transfer requests.
    /// 分配批次 ID，用于提交一组传输请求。
    ///
    /// Returns `INVALID_BATCH` (u64::MAX) on failure. The batch_id must be
    /// freed with `free_batch_id` after all transfers complete.
    /// 失败时返回 `INVALID_BATCH` (u64::MAX)。所有传输完成后必须用
    /// `free_batch_id` 释放 batch_id。
    ///
    /// `batch_size` should match the number of requests you plan to submit.
    /// `batch_size` 应与你计划提交的请求数量匹配。
    pub fn allocate_owned_batch_id(&self, batch_size: usize) -> TransferEngineResult<OwnedBatchId> {
        tracing::info!(target: "te_debug", batch_size, "allocate_batch_id: calling C API");
        let id = unsafe { ffi::allocateBatchID(self.handle.as_ptr(), batch_size) };
        tracing::info!(target: "te_debug", batch_size, batch_id = id, "allocate_batch_id: C API returned");
        if id == u64::MAX {
            tracing::error!(target: "te_debug", batch_size, "allocate_batch_id: INVALID_BATCH");
            return Err(TransferEngineError::OperationFailed(-1));
        }
        Ok(OwnedBatchId::allocated(id, self.instance_id))
    }

    /// Submit a batch of transfer requests.
    /// 提交一批传输请求。
    ///
    /// Each request specifies an opcode (Read/Write), source buffer,
    /// target segment ID, target offset, and length. All requests in
    /// a batch are submitted atomically to the transport layer.
    /// 每个请求指定操作码（读/写）、源缓冲区、目标段 ID、
    /// 目标偏移量和长度。批次中的所有请求原子性地提交到传输层。
    /// # Safety
    ///
    /// Every request's `source` range must be valid and registered for the
    /// requested access, and must remain alive and unavailable for conflicting
    /// Rust access until every submitted task is quiescent in the native
    /// engine. Returning from this function does not end native access.
    pub unsafe fn submit_owned_transfer(
        &self,
        batch_id: &OwnedBatchId,
        requests: &[TransferRequest],
    ) -> TransferEngineResult<()> {
        let raw_batch_id = batch_id.validate_for(self.instance_id)?;
        tracing::info!(
            target: "te_debug",
            batch_id = raw_batch_id,
            req_count = requests.len(),
            "submit_transfer: calling C API"
        );
        // 该 Vec 让 C layout 描述在 submitTransfer 调用期间地址稳定；它不拥有 source
        // payload，异步完成前保持 payload 有效仍是上层调用者的责任。
        let mut ffi_requests: Vec<ffi::transfer_request_t> = requests
            .iter()
            .enumerate()
            .map(|(i, r)| {
                tracing::info!(
                    target: "te_debug",
                    batch_id = raw_batch_id,
                    idx = i,
                    opcode = r.opcode as i32,
                    src = ?r.source,
                    tgt_id = r.target_id.0,
                    tgt_off = r.target_offset,
                    len = r.length,
                    "submit_transfer: request detail"
                );
                ffi::transfer_request_t {
                    opcode: r.opcode as i32,
                    source: r.source,
                    target_id: r.target_id.0,
                    target_offset: r.target_offset,
                    length: r.length,
                }
            })
            .collect();

        let rc = unsafe {
            ffi::submitTransfer(
                self.handle.as_ptr(),
                raw_batch_id,
                ffi_requests.as_mut_ptr(),
                ffi_requests.len(),
            )
        };
        tracing::info!(target: "te_debug", batch_id = raw_batch_id, rc, "submit_transfer: C API returned");
        if rc != 0 {
            tracing::error!(target: "te_debug", batch_id = raw_batch_id, rc, "submit_transfer: FAILED");
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Poll the status of a single transfer within a batch.
    /// 轮询批次中单个传输任务的状态。
    ///
    /// `task_id` is the index of the request within the batch (0-based).
    /// Returns a `TransferStatus` with the current status enum and the
    /// number of bytes transferred so far.
    /// `task_id` 是请求在批次中的索引（从 0 开始）。
    /// 返回 `TransferStatus`，包含当前状态枚举和已传输的字节数。
    ///
    /// # Polling Pattern / 轮询模式
    ///
    /// After calling `submit_transfer`, the caller should poll each task
    /// until its status becomes terminal (`Completed`, `Failed`, `Canceled`,
    /// or `Timeout`). Non-terminal states (`Waiting`, `Pending`) mean the
    /// transfer is still in progress.
    /// 调用 `submit_transfer` 后，调用者应轮询每个任务直到其状态变为终态
    /// （`Completed`、`Failed`、`Canceled` 或 `Timeout`）。
    /// 非终态（`Waiting`、`Pending`）表示传输仍在进行中。
    pub fn get_owned_transfer_status(
        &self,
        batch_id: &OwnedBatchId,
        task_id: usize,
    ) -> TransferEngineResult<TransferStatus> {
        let raw_batch_id = batch_id.validate_for(self.instance_id)?;
        let mut status = ffi::transfer_status_t {
            status: 0,
            transferred_bytes: 0,
        };
        let rc = unsafe {
            ffi::getTransferStatus(self.handle.as_ptr(), raw_batch_id, task_id, &mut status)
        };
        if rc != 0 {
            tracing::error!(
                target: "te_debug",
                batch_id = raw_batch_id,
                task_id,
                rc,
                "get_transfer_status: FAILED"
            );
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(TransferStatus {
            status: TransferStatusEnum::from_i32(status.status),
            transferred_bytes: status.transferred_bytes,
        })
    }

    /// Poll the aggregate status of a batch.
    /// 轮询整个批次的聚合传输状态。
    pub fn get_owned_batch_transfer_status(
        &self,
        batch_id: &OwnedBatchId,
    ) -> TransferEngineResult<TransferStatus> {
        let raw_batch_id = batch_id.validate_for(self.instance_id)?;
        let mut status = ffi::transfer_status_t {
            status: 0,
            transferred_bytes: 0,
        };
        let rc =
            unsafe { ffi::getBatchTransferStatus(self.handle.as_ptr(), raw_batch_id, &mut status) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(TransferStatus {
            status: TransferStatusEnum::from_i32(status.status),
            transferred_bytes: status.transferred_bytes,
        })
    }

    /// Release a batch ID after all transfers complete.
    /// 在所有传输完成后释放批次 ID。
    ///
    /// Must be called after all tasks in the batch have reached a terminal
    /// state. Failing to free a batch leaks resources in the C++ engine.
    /// 必须在批次中所有任务达到终态后调用。
    /// 未能释放批次会导致 C++ 引擎中的资源泄漏。
    pub fn free_owned_batch_id(&self, batch_id: &mut OwnedBatchId) -> TransferEngineResult<()> {
        let raw_batch_id = batch_id.validate_for(self.instance_id)?;
        tracing::info!(target: "te_debug", batch_id = raw_batch_id, "free_batch_id: calling C API");
        let rc = unsafe { ffi::freeBatchID(self.handle.as_ptr(), raw_batch_id) };
        tracing::info!(target: "te_debug", batch_id = raw_batch_id, rc, "free_batch_id: C API returned");
        // The current Status C API returns the positive enum value (4);
        // older error.h-based adapters used -4.
        if matches!(rc, 4 | -4) {
            return Err(TransferEngineError::BatchBusy);
        }
        if rc != 0 {
            tracing::error!(target: "te_debug", batch_id = raw_batch_id, rc, "free_batch_id: FAILED");
            return Err(TransferEngineError::OperationFailed(rc));
        }
        batch_id.mark_released();
        Ok(())
    }

    // -----------------------------------------------------------------------
    // Transfer with notification / 带通知的传输
    // -----------------------------------------------------------------------
    // In addition to polling, the engine supports a notification mechanism
    // where the sender can attach a message that is delivered to the receiver
    // upon transfer completion.
    // 除了轮询，引擎还支持通知机制，发送方可以附加一条消息，
    // 传输完成时该消息会传递给接收方。

    /// Submit a batch of transfer requests and send a notification on completion.
    /// 提交一批传输请求，并在完成时发送通知。
    ///
    /// The `notify_msg` contains a target name and a message string. The
    /// notification is delivered asynchronously to the target peer.
    /// `notify_msg` 包含目标名称和消息字符串。通知异步传递给目标节点。
    /// # Safety
    ///
    /// The same payload lifetime, registration, bounds, and aliasing
    /// requirements as [`Self::submit_owned_transfer`] apply.
    pub unsafe fn submit_owned_transfer_with_notify(
        &self,
        batch_id: &OwnedBatchId,
        requests: &[TransferRequest],
        notify_msg: &NotifyMsg,
    ) -> TransferEngineResult<()> {
        let raw_batch_id = batch_id.validate_for(self.instance_id)?;
        let mut ffi_requests: Vec<ffi::transfer_request_t> = requests
            .iter()
            .map(|r| ffi::transfer_request_t {
                opcode: r.opcode as i32,
                source: r.source,
                target_id: r.target_id.0,
                target_offset: r.target_offset,
                length: r.length,
            })
            .collect();

        let name_c = CString::new(notify_msg.name.as_str())?;
        let msg_c = CString::new(notify_msg.msg.as_str())?;
        let ffi_notify = ffi::notify_msg_t {
            name: name_c.as_ptr() as *mut std::os::raw::c_char,
            msg: msg_c.as_ptr() as *mut std::os::raw::c_char,
        };

        let rc = unsafe {
            ffi::submitTransferWithNotify(
                self.handle.as_ptr(),
                raw_batch_id,
                ffi_requests.as_mut_ptr(),
                ffi_requests.len(),
                ffi_notify,
            )
        };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Generate a notification message and send it to a target peer.
    /// 生成通知消息并发送给目标节点。
    ///
    /// Unlike `submit_transfer_with_notify`, this sends a standalone
    /// notification without an associated data transfer.
    /// 与 `submit_transfer_with_notify` 不同，此方法发送独立的通知，
    /// 不关联数据传输。
    pub fn gen_notify_in_engine(
        &self,
        target_id: u64,
        notify_msg: &NotifyMsg,
    ) -> TransferEngineResult<()> {
        let name_c = CString::new(notify_msg.name.as_str())?;
        let msg_c = CString::new(notify_msg.msg.as_str())?;
        let ffi_notify = ffi::notify_msg_t {
            name: name_c.as_ptr() as *mut std::os::raw::c_char,
            msg: msg_c.as_ptr() as *mut std::os::raw::c_char,
        };
        let rc = unsafe { ffi::genNotifyInEngine(self.handle.as_ptr(), target_id, ffi_notify) };
        if rc != 0 {
            return Err(TransferEngineError::OperationFailed(rc));
        }
        Ok(())
    }

    /// Probe whether a peer segment is alive.
    /// 探测目标 peer segment 是否存活。
    pub fn probe_peer_alive_by_id(&self, target_id: SegmentId) -> bool {
        unsafe { ffi::probePeerAliveByID(self.handle.as_ptr(), target_id.0) == 0 }
    }

    /// Return true when TCP is the only installed transport.
    /// 当 TCP 是唯一安装的传输协议时返回 true。
    pub fn is_tcp_only(&self) -> bool {
        unsafe { ffi::isTcpOnly(self.handle.as_ptr()) != 0 }
    }

    /// Check whether a memory range overlaps an already registered region.
    /// 检查内存范围是否与已注册区域重叠。
    ///
    /// # Safety
    /// `addr` and `length` must describe the caller-owned memory range to check.
    pub unsafe fn check_overlap(&self, addr: *mut c_void, length: u64) -> bool {
        unsafe { ffi::checkOverlap(self.handle.as_ptr(), addr, length) != 0 }
    }

    /// Toggle automatic topology discovery in the native engine.
    /// 切换 native engine 的自动拓扑发现开关。
    pub fn set_auto_discover(&self, auto_discover: bool) {
        unsafe { ffi::setAutoDiscover(self.handle.as_ptr(), auto_discover as i32) };
    }

    /// Get the native base address used by transports that expose one.
    /// 获取传输层暴露的 native base address。
    ///
    /// # Safety
    /// The returned pointer is owned by the native engine and must not be freed.
    pub unsafe fn get_base_addr(&self) -> *mut c_void {
        unsafe { ffi::getBaseAddr(self.handle.as_ptr()) }
    }

    /// Poll for incoming notification messages.
    /// 轮询接收到的通知消息。
    ///
    /// Returns all pending notifications. The C++ layer allocates a buffer
    /// that is freed after Rust has copied the data.
    /// 返回所有待处理的通知。C++ 层分配的缓冲区在 Rust 复制数据后释放。
    pub fn get_notifs_from_engine(&self) -> TransferEngineResult<Vec<NotifyMsg>> {
        let mut size: i32 = 0;
        let raw = unsafe { ffi::getNotifsFromEngine(self.handle.as_ptr(), &mut size) };
        if size < 0 {
            let _guard = NativeNotifyBuffer { raw, count: size };
            return Err(TransferEngineError::InvalidNotificationBuffer(
                "negative entry count",
            ));
        }
        if raw.is_null() {
            return if size == 0 {
                Ok(Vec::new())
            } else {
                Err(TransferEngineError::InvalidNotificationBuffer(
                    "null entries with non-zero count",
                ))
            };
        }
        let guard = NativeNotifyBuffer { raw, count: size };
        let count = usize::try_from(size)?;
        let mut out = Vec::with_capacity(count);
        for i in 0..count {
            let entry = unsafe { &*guard.raw.add(i) };
            if entry.name.is_null() || entry.msg.is_null() {
                return Err(TransferEngineError::InvalidNotificationBuffer(
                    "null entry string",
                ));
            }
            let name = unsafe { CStr::from_ptr(entry.name) }.to_str()?.to_string();
            let msg = unsafe { CStr::from_ptr(entry.msg) }.to_str()?.to_string();
            out.push(NotifyMsg { name, msg });
        }
        Ok(out)
    }
}

impl Drop for TransferEngine {
    fn drop(&mut self) {
        // Destroy the C++ TransferEngine instance, freeing all resources:
        // registered memory, open segments, transport connections, etc.
        // 销毁 C++ TransferEngine 实例，释放所有资源：
        // 注册的内存、打开的段、传输连接等。
        unsafe {
            ffi::destroyTransferEngine(self.handle.as_ptr());
        }
    }
}
