[package]
name = "transfer-engine-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
mock = []
link-native = []
link-tent-native = ["link-native"]

[lib]
name = "transfer_engine_ffi"

[dependencies]
thiserror.workspace = true
libc.workspace = true
tracing.workspace = true

[build-dependencies]
bindgen.workspace = true
