use super::offset::{RECORD_HEADER_SIZE, RecordHeader};
use super::{
    LocalStorageBackend, LocalStorageConfig, decode_file_per_key_record,
    encode_file_per_key_record, local_storage_key, sync_directory,
};
use super::{
    OffsetAllocatorConfig, OffsetAllocatorStorageBackend, OffsetEvictionPolicy, OffsetPersistMode,
    OffsetPersistenceConfig,
};
use mooncake_store_core::StoreError;
use mooncake_store_core::error::StoreResult;
use prost::Message;
use sha2::{Digest, Sha256};
use std::collections::{HashMap, HashSet};
#[cfg(unix)]
use std::ffi::CString;
use std::io::{Read, Seek, SeekFrom};
#[cfg(unix)]
use std::os::unix::ffi::OsStrExt;
use std::path::{Path, PathBuf};
use std::time::UNIX_EPOCH;
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FilePerKeyMigrationReport {
    pub object_count: usize,
    pub value_bytes: u64,
    pub encoded_bytes: u64,
    pub target_data_dir: PathBuf,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct OffsetAllocatorMigrationReport {
    pub object_count: usize,
    pub skipped_record_count: usize,
    pub unverified_object_count: usize,
    pub value_bytes: u64,
    pub encoded_bytes: u64,
    pub source_capacity_bytes: u64,
    pub target_data_dir: PathBuf,
}

#[derive(Clone, PartialEq, Message)]
struct CppPersistedFifoEntry {
    #[prost(uint64, tag = "1")]
    seq: u64,
    #[prost(string, tag = "2")]
    key: String,
}

#[derive(Clone, PartialEq, Message)]
struct CppOffsetAllocatorMetadata {
    #[prost(uint32, tag = "1")]
    version: u32,
    #[prost(bytes = "vec", tag = "2")]
    allocator_state: Vec<u8>,
    #[prost(uint64, tag = "3")]
    insert_seq: u64,
    #[prost(message, repeated, tag = "4")]
    fifo_entries: Vec<CppPersistedFifoEntry>,
    #[prost(string, repeated, tag = "5")]
    evicted_keys_this_batch: Vec<String>,
}

#[derive(Debug)]
struct CppOffsetRecord {
    source_key: String,
    storage_key: String,
    offset: u64,
    record_size: u64,
    value_offset: u64,
    value_size: u64,
    write_seq: u64,
    has_crc: bool,
    record_sha256: [u8; 32],
}

#[derive(Debug)]
struct CppAllocatorImage {
    capacity: u64,
    allocated_size: u64,
    used_extents: Vec<(u64, u64)>,
}

#[derive(Debug)]
struct SourceRecord {
    path: PathBuf,
    source_key: String,
    storage_key: String,
    value_size: u64,
    encoded_size: u64,
    source_sha256: [u8; 32],
}

struct StagingDirectory {
    path: PathBuf,
    lock_path: PathBuf,
    armed: bool,
}

impl StagingDirectory {
    fn new(path: PathBuf, lock_path: PathBuf) -> Self {
        Self {
            path,
            lock_path,
            armed: true,
        }
    }

    fn disarm(&mut self) {
        self.armed = false;
    }
}

impl Drop for StagingDirectory {
    fn drop(&mut self) {
        if self.armed {
            let _ = std::fs::remove_dir_all(&self.path);
            let _ = std::fs::remove_file(&self.lock_path);
        }
    }
}

/// Migrate a C++ FilePerKey directory into the canonical Rust layout.
///
/// C++ `KVEntry` files are standard protobuf messages generated by
/// `YLT_REFL(KVEntry, key, value)`: field 1 is the key and field 2 is the
/// value. The migration is deliberately offline and publishes through an
/// atomic directory rename:
///
/// 1. parse and validate every source record without changing either tree;
/// 2. reject duplicate/scoped keys and insufficient configured quota;
/// 3. write and verify a unique staging directory;
/// 4. rename the staging directory to the final `root_dir/fsdir`.
///
/// `default_tenant_id` is used for legacy C++ keys without a `tenant\0key`
/// prefix. A C++ key that already contains that prefix preserves its tenant.
/// The source directory is never modified.
pub fn migrate_cpp_file_per_key_layout(
    source_data_dir: impl AsRef<Path>,
    target_config: LocalStorageConfig,
    default_tenant_id: &str,
) -> StoreResult<FilePerKeyMigrationReport> {
    validate_default_tenant(default_tenant_id)?;
    let source_data_dir = source_data_dir.as_ref();
    if !source_data_dir.is_dir() {
        return Err(StoreError::InvalidParams(format!(
            "C++ FilePerKey source is not a directory: {}",
            source_data_dir.display()
        )));
    }
    if target_config.fsdir.trim().is_empty() {
        return Err(StoreError::InvalidParams(
            "FilePerKey migration target fsdir must not be empty".to_string(),
        ));
    }
    let mut fsdir_components = Path::new(&target_config.fsdir).components();
    if !matches!(
        (fsdir_components.next(), fsdir_components.next()),
        (Some(std::path::Component::Normal(_)), None)
    ) {
        return Err(StoreError::InvalidParams(
            "FilePerKey migration target fsdir must be exactly one normal path component"
                .to_string(),
        ));
    }

    let target_data_dir = target_config.root_dir.join(&target_config.fsdir);
    if target_data_dir.exists() {
        return Err(StoreError::InvalidParams(format!(
            "FilePerKey migration target already exists: {}",
            target_data_dir.display()
        )));
    }
    std::fs::create_dir_all(&target_config.root_dir)?;
    let canonical_source = std::fs::canonicalize(source_data_dir)?;
    let canonical_target_root = std::fs::canonicalize(&target_config.root_dir)?;
    let canonical_target = canonical_target_root.join(&target_config.fsdir);
    if canonical_target.starts_with(&canonical_source)
        || canonical_source.starts_with(&canonical_target)
    {
        return Err(StoreError::InvalidParams(format!(
            "FilePerKey migration source and target must not overlap: source={}, target={}",
            canonical_source.display(),
            canonical_target.display()
        )));
    }

    let source_files = collect_source_files(source_data_dir)?;
    let mut records = Vec::with_capacity(source_files.len());
    let mut storage_keys = HashSet::with_capacity(source_files.len());
    let mut value_bytes = 0_u64;
    let mut encoded_bytes = 0_u64;
    for path in &source_files {
        let bytes = std::fs::read(path)?;
        let (source_key, value) = decode_file_per_key_record(&bytes).map_err(|error| {
            StoreError::InvalidParams(format!(
                "invalid C++ FilePerKey record {}: {error}",
                path.display()
            ))
        })?;
        let storage_key = scoped_storage_key(source_key, default_tenant_id)?;
        if !storage_keys.insert(storage_key.clone()) {
            return Err(StoreError::InvalidParams(format!(
                "duplicate FilePerKey key after tenant scoping: {storage_key:?}"
            )));
        }
        let canonical = encode_file_per_key_record(&storage_key, value)?;
        value_bytes = value_bytes.checked_add(value.len() as u64).ok_or_else(|| {
            StoreError::InvalidParams("migration value size overflow".to_string())
        })?;
        encoded_bytes = encoded_bytes
            .checked_add(canonical.len() as u64)
            .ok_or_else(|| {
                StoreError::InvalidParams("migration encoded size overflow".to_string())
            })?;
        records.push(SourceRecord {
            path: path.clone(),
            source_key: source_key.to_string(),
            storage_key,
            value_size: value.len() as u64,
            encoded_size: canonical.len() as u64,
            source_sha256: Sha256::digest(&bytes).into(),
        });
    }
    if target_config.quota_bytes > 0 && encoded_bytes > target_config.quota_bytes {
        return Err(StoreError::NoAvailableHandle);
    }

    let staging_name = format!(".mooncake-file-per-key-migration-{}", Uuid::new_v4());
    let staging_path = target_config.root_dir.join(&staging_name);
    let staging_lock_path = target_config
        .root_dir
        .join(format!(".{staging_name}.mooncake-storage.lock"));
    let mut staging = StagingDirectory::new(staging_path.clone(), staging_lock_path.clone());
    let mut staging_config = target_config.clone();
    staging_config.fsdir = staging_name;
    staging_config.enable_eviction = false;
    staging_config.quota_bytes = 0;

    {
        let backend = LocalStorageBackend::new_persistent(staging_config);
        backend.init()?;
        for record in &records {
            let bytes = std::fs::read(&record.path)?;
            let (source_key, value) = decode_file_per_key_record(&bytes)?;
            if source_key != record.source_key
                || value.len() as u64 != record.value_size
                || <[u8; 32]>::from(Sha256::digest(&bytes)) != record.source_sha256
                || encode_file_per_key_record(&record.storage_key, value)?.len() as u64
                    != record.encoded_size
            {
                return Err(StoreError::InvalidParams(format!(
                    "C++ FilePerKey source changed during migration: {}",
                    record.path.display()
                )));
            }
            backend.write_object(&record.storage_key, value)?;
            if backend.read_object(&record.storage_key)? != value {
                return Err(StoreError::Internal(format!(
                    "FilePerKey staging read-back mismatch for key {:?}",
                    record.storage_key
                )));
            }
        }

        let metadata = backend.scan_meta()?;
        let migrated = metadata
            .iter()
            .map(|(key, size)| (key.as_str(), *size))
            .collect::<HashSet<_>>();
        let expected = records
            .iter()
            .map(|record| (record.storage_key.as_str(), record.value_size))
            .collect::<HashSet<_>>();
        if migrated != expected {
            return Err(StoreError::Internal(
                "FilePerKey staging verification did not match the source key/value sizes"
                    .to_string(),
            ));
        }
    }

    let final_source_files = collect_source_files(source_data_dir)?;
    if final_source_files != source_files {
        return Err(StoreError::InvalidParams(
            "C++ FilePerKey source file set changed during migration".to_string(),
        ));
    }
    for record in &records {
        let bytes = std::fs::read(&record.path)?;
        if <[u8; 32]>::from(Sha256::digest(&bytes)) != record.source_sha256 {
            return Err(StoreError::InvalidParams(format!(
                "C++ FilePerKey source changed before migration publish: {}",
                record.path.display()
            )));
        }
    }
    match std::fs::remove_file(&staging_lock_path) {
        Ok(()) => sync_directory(&target_config.root_dir)?,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => return Err(error.into()),
    }
    sync_directory_tree(&staging_path)?;
    if target_data_dir.exists() {
        return Err(StoreError::InvalidParams(format!(
            "FilePerKey migration target appeared before publish: {}",
            target_data_dir.display()
        )));
    }
    rename_directory_noreplace(&staging_path, &target_data_dir)?;
    staging.disarm();
    if let Err(error) = sync_directory(&target_config.root_dir) {
        return Err(StoreError::Internal(format!(
            "FilePerKey migration target was installed at {} but parent directory sync failed: \
             {error}",
            target_data_dir.display()
        )));
    }

    Ok(FilePerKeyMigrationReport {
        object_count: records.len(),
        value_bytes,
        encoded_bytes,
        target_data_dir,
    })
}

/// Migrate a C++ OffsetAllocator v3 checkpoint into the Rust allocator layout.
///
/// This is an offline, one-way importer. It never opens the C++ directory as a
/// Rust backend and never modifies `kv_cache.data` or `kv_cache.meta`. The
/// complete C++ checkpoint is validated before a unique Rust staging directory
/// is written and read back; publication is an atomic no-replace rename.
///
/// The caller must stop every C++ writer and keep the source directory
/// quiescent for the whole call. Identity/hash checks detect ordinary accidental
/// changes, but the C++ format exposes no interoperable ownership lock that
/// could make this precondition enforceable from Rust.
pub fn migrate_cpp_offset_allocator_layout(
    source_data_dir: impl AsRef<Path>,
    mut target_config: OffsetAllocatorConfig,
    default_tenant_id: &str,
) -> StoreResult<OffsetAllocatorMigrationReport> {
    const CPP_METADATA_VERSION: u32 = 3;
    validate_default_tenant(default_tenant_id)?;
    validate_single_component(
        &target_config.fsdir,
        "OffsetAllocator migration target fsdir",
    )?;
    target_config
        .validate()
        .map_err(StoreError::InvalidParams)?;
    target_config.eviction_policy = OffsetEvictionPolicy::None;

    let source_data_dir = source_data_dir.as_ref();
    if !source_data_dir.is_dir() {
        return Err(StoreError::InvalidParams(format!(
            "C++ OffsetAllocator source is not a directory: {}",
            source_data_dir.display()
        )));
    }
    let source_data_path = source_data_dir.join("kv_cache.data");
    let source_meta_path = source_data_dir.join("kv_cache.meta");
    validate_regular_file(&source_data_path, "C++ OffsetAllocator data")?;
    validate_regular_file(&source_meta_path, "C++ OffsetAllocator metadata")?;

    let target_data_dir = target_config.root_dir.join(&target_config.fsdir);
    if target_data_dir.exists() {
        return Err(StoreError::InvalidParams(format!(
            "OffsetAllocator migration target already exists: {}",
            target_data_dir.display()
        )));
    }
    std::fs::create_dir_all(&target_config.root_dir)?;
    reject_overlapping_trees(
        source_data_dir,
        &target_config.root_dir,
        &target_config.fsdir,
    )?;

    let meta_bytes = std::fs::read(&source_meta_path)?;
    let meta_sha256: [u8; 32] = Sha256::digest(&meta_bytes).into();
    let metadata = CppOffsetAllocatorMetadata::decode(meta_bytes.as_slice()).map_err(|error| {
        StoreError::InvalidParams(format!(
            "invalid C++ OffsetAllocator protobuf metadata: {error}"
        ))
    })?;
    if metadata.encode_to_vec() != meta_bytes {
        return Err(StoreError::InvalidParams(
            "C++ OffsetAllocator metadata is not the canonical v3 protobuf encoding".to_string(),
        ));
    }
    if metadata.version != CPP_METADATA_VERSION {
        return Err(StoreError::InvalidParams(format!(
            "unsupported C++ OffsetAllocator metadata version {}; expected {CPP_METADATA_VERSION}",
            metadata.version
        )));
    }
    let allocator = decode_cpp_allocator_image(&metadata.allocator_state)?;
    let source_data_metadata = std::fs::metadata(&source_data_path)?;
    if source_data_metadata.len() != allocator.capacity {
        return Err(StoreError::InvalidParams(format!(
            "C++ OffsetAllocator data file size differs from allocator capacity: {} != {}",
            source_data_metadata.len(),
            allocator.capacity
        )));
    }
    let source_data_identity = source_file_identity(&source_data_metadata);
    let evicted = metadata
        .evicted_keys_this_batch
        .iter()
        .map(String::as_str)
        .collect::<HashSet<_>>();
    let mut source_file = std::fs::File::open(&source_data_path)?;
    let mut by_source_key = HashMap::<String, CppOffsetRecord>::new();
    let mut parsed_allocated_size = 0_u64;
    let mut skipped_record_count = 0_usize;
    for &(offset, allocated_size) in &allocator.used_extents {
        let Some(record) = read_cpp_offset_record(
            &mut source_file,
            offset,
            allocated_size,
            allocator.capacity,
            metadata.insert_seq,
            default_tenant_id,
        )?
        else {
            skipped_record_count += 1;
            continue;
        };
        parsed_allocated_size = parsed_allocated_size
            .checked_add(record.record_size)
            .ok_or_else(|| {
                StoreError::InvalidParams("C++ OffsetAllocator allocated size overflow".to_string())
            })?;
        if evicted.contains(record.source_key.as_str()) {
            continue;
        }
        match by_source_key.entry(record.source_key.clone()) {
            std::collections::hash_map::Entry::Vacant(entry) => {
                entry.insert(record);
            }
            std::collections::hash_map::Entry::Occupied(mut entry) => {
                if entry.get().write_seq == record.write_seq {
                    return Err(StoreError::InvalidParams(format!(
                        "C++ OffsetAllocator contains duplicate key {:?} at the same sequence {}",
                        record.source_key, record.write_seq
                    )));
                }
                if entry.get().write_seq < record.write_seq {
                    entry.insert(record);
                }
            }
        }
    }
    if skipped_record_count == 0 && parsed_allocated_size != allocator.allocated_size {
        return Err(StoreError::InvalidParams(format!(
            "C++ OffsetAllocator allocated_size mismatch: header={}, records={parsed_allocated_size}",
            allocator.allocated_size
        )));
    }

    let mut fifo_by_key = HashMap::with_capacity(metadata.fifo_entries.len());
    let mut fifo_sequences = HashSet::with_capacity(metadata.fifo_entries.len());
    for entry in &metadata.fifo_entries {
        if entry.seq >= metadata.insert_seq
            || !by_source_key.contains_key(&entry.key)
            || !fifo_sequences.insert(entry.seq)
            || fifo_by_key.contains_key(entry.key.as_str())
        {
            continue;
        }
        fifo_by_key.insert(entry.key.clone(), entry.seq);
    }
    let mut records = by_source_key.into_values().collect::<Vec<_>>();
    let mut repair_order = records
        .iter()
        .filter(|record| !fifo_by_key.contains_key(record.source_key.as_str()))
        .map(|record| (record.write_seq, record.source_key.clone(), record.offset))
        .collect::<Vec<_>>();
    repair_order.sort_unstable();
    let mut next_repair_seq = metadata
        .fifo_entries
        .iter()
        .map(|entry| entry.seq)
        .max()
        .unwrap_or(metadata.insert_seq)
        .max(metadata.insert_seq)
        .saturating_add(1);
    for (_, key, _) in repair_order {
        fifo_by_key.insert(key, next_repair_seq);
        next_repair_seq = next_repair_seq.saturating_add(1);
    }
    records.sort_unstable_by(|left, right| {
        fifo_by_key[left.source_key.as_str()]
            .cmp(&fifo_by_key[right.source_key.as_str()])
            .then_with(|| left.storage_key.cmp(&right.storage_key))
    });
    let mut scoped_keys = HashSet::with_capacity(records.len());
    let mut value_bytes = 0_u64;
    let mut encoded_bytes = 0_u64;
    for record in &records {
        if !scoped_keys.insert(record.storage_key.as_str()) {
            return Err(StoreError::InvalidParams(format!(
                "duplicate C++ OffsetAllocator key after tenant scoping: {:?}",
                record.storage_key
            )));
        }
        value_bytes = value_bytes.checked_add(record.value_size).ok_or_else(|| {
            StoreError::InvalidParams("OffsetAllocator migration value size overflow".to_string())
        })?;
        let target_record_size =
            RecordHeader::record_size(record.storage_key.len() as u64, record.value_size).map_err(
                |error| {
                    StoreError::InvalidParams(format!(
                        "scoped OffsetAllocator record is not representable: {}",
                        error.0
                    ))
                },
            )?;
        encoded_bytes = encoded_bytes
            .checked_add(target_record_size)
            .ok_or_else(|| {
                StoreError::InvalidParams(
                    "OffsetAllocator migration encoded size overflow".to_string(),
                )
            })?;
    }
    if records.len() > target_config.total_keys_limit
        || (target_config.quota_bytes > 0 && encoded_bytes > target_config.quota_bytes)
    {
        return Err(StoreError::NoAvailableHandle);
    }

    let staging_name = format!(".mooncake-offset-migration-{}", Uuid::new_v4());
    let staging_path = target_config.root_dir.join(&staging_name);
    let mut staging = StagingDirectory::new(staging_path.clone(), staging_path.join(".unused"));
    let mut staging_config = target_config.clone();
    staging_config.fsdir = staging_name;
    let persistence = OffsetPersistenceConfig {
        persist_mode: OffsetPersistMode::Strict,
        persist_interval_seconds: 60,
        enable_record_crc: true,
    };
    {
        let backend =
            OffsetAllocatorStorageBackend::new_with_persistence(staging_config, persistence);
        backend.init()?;
        for record in &records {
            let value = reread_cpp_offset_value(&mut source_file, record)?;
            backend.write_object(&record.storage_key, &value)?;
            if backend.read_object(&record.storage_key)? != value {
                return Err(StoreError::Internal(format!(
                    "OffsetAllocator staging read-back mismatch for key {:?}",
                    record.storage_key
                )));
            }
        }
        let migrated = backend.scan_meta()?.into_iter().collect::<HashSet<_>>();
        let expected = records
            .iter()
            .map(|record| (record.storage_key.clone(), record.value_size))
            .collect::<HashSet<_>>();
        if migrated != expected {
            return Err(StoreError::Internal(
                "OffsetAllocator staging verification did not match source key/value sizes"
                    .to_string(),
            ));
        }
    }

    verify_cpp_offset_source(
        &source_data_path,
        &source_meta_path,
        source_data_identity,
        meta_sha256,
        &records,
    )?;
    sync_directory_tree(&staging_path)?;
    if target_data_dir.exists() {
        return Err(StoreError::InvalidParams(format!(
            "OffsetAllocator migration target appeared before publish: {}",
            target_data_dir.display()
        )));
    }
    rename_directory_noreplace(&staging_path, &target_data_dir)?;
    staging.disarm();
    if let Err(error) = sync_directory(&target_config.root_dir) {
        return Err(StoreError::Internal(format!(
            "OffsetAllocator migration target was installed at {} but parent directory sync \
             failed: {error}",
            target_data_dir.display()
        )));
    }

    Ok(OffsetAllocatorMigrationReport {
        object_count: records.len(),
        skipped_record_count,
        unverified_object_count: records.iter().filter(|record| !record.has_crc).count(),
        value_bytes,
        encoded_bytes,
        source_capacity_bytes: allocator.capacity,
        target_data_dir,
    })
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct SourceFileIdentity {
    len: u64,
    device: u64,
    inode: u64,
    modified_nanos: u128,
}

#[cfg(unix)]
fn source_file_identity(metadata: &std::fs::Metadata) -> SourceFileIdentity {
    use std::os::unix::fs::MetadataExt;
    SourceFileIdentity {
        len: metadata.len(),
        device: metadata.dev(),
        inode: metadata.ino(),
        modified_nanos: metadata
            .modified()
            .ok()
            .and_then(|time| time.duration_since(UNIX_EPOCH).ok())
            .map_or(0, |duration| duration.as_nanos()),
    }
}

#[cfg(not(unix))]
fn source_file_identity(metadata: &std::fs::Metadata) -> SourceFileIdentity {
    SourceFileIdentity {
        len: metadata.len(),
        device: 0,
        inode: 0,
        modified_nanos: metadata
            .modified()
            .ok()
            .and_then(|time| time.duration_since(UNIX_EPOCH).ok())
            .map_or(0, |duration| duration.as_nanos()),
    }
}

fn decode_cpp_allocator_image(bytes: &[u8]) -> StoreResult<CppAllocatorImage> {
    const OUTER_HEADER_SIZE: usize = 5 * 8;
    const TOP_BINS: usize = 32;
    const LEAF_BINS: usize = 256;
    const INNER_HEADER_SIZE: usize = 5 * 4 + TOP_BINS + LEAF_BINS * 4 + 4;
    const NODE_SIZE: usize = 28;
    const FREE_NODE_SIZE: usize = 4;
    const MAX_SERIALIZED_NODES: u32 = 1 << 24;

    if !cfg!(target_endian = "little") {
        return Err(StoreError::InvalidParams(
            "C++ OffsetAllocator v3 migration only supports the known little-endian native ABI"
                .to_string(),
        ));
    }
    if bytes.len() < OUTER_HEADER_SIZE + INNER_HEADER_SIZE {
        return Err(StoreError::InvalidParams(
            "truncated C++ OffsetAllocator allocator_state".to_string(),
        ));
    }
    let base = read_u64_le(bytes, 0)?;
    let multiplier_bits = read_u64_le(bytes, 8)?;
    let capacity = read_u64_le(bytes, 16)?;
    let allocated_size = read_u64_le(bytes, 24)?;
    let allocated_num = read_u64_le(bytes, 32)?;
    if base != 0 || multiplier_bits >= 32 || capacity == 0 {
        return Err(StoreError::InvalidParams(format!(
            "invalid C++ OffsetAllocator header: base={base}, \
             multiplier_bits={multiplier_bits}, capacity={capacity}"
        )));
    }

    let inner = OUTER_HEADER_SIZE;
    let size = read_u32_le(bytes, inner)?;
    let current_capacity = read_u32_le(bytes, inner + 4)?;
    let max_capacity = read_u32_le(bytes, inner + 8)?;
    let free_storage = read_u32_le(bytes, inner + 12)?;
    let free_offset_position = inner + 5 * 4 + TOP_BINS + LEAF_BINS * 4;
    let free_offset = read_u32_le(bytes, free_offset_position)?;
    if size == 0
        || current_capacity == 0
        || u64::from(size) != (capacity >> multiplier_bits)
        || max_capacity == 0
        || max_capacity > MAX_SERIALIZED_NODES
        || current_capacity > max_capacity
        || free_offset > current_capacity
    {
        return Err(StoreError::InvalidParams(format!(
            "invalid C++ OffsetAllocator internal capacities: size={size}, \
             current={current_capacity}, max={max_capacity}, free_offset={free_offset}"
        )));
    }
    let nodes_size = (current_capacity as usize)
        .checked_mul(NODE_SIZE)
        .ok_or_else(|| {
            StoreError::InvalidParams("C++ OffsetAllocator node size overflow".to_string())
        })?;
    let free_nodes_size = (current_capacity as usize)
        .checked_mul(FREE_NODE_SIZE)
        .ok_or_else(|| {
            StoreError::InvalidParams("C++ OffsetAllocator free-node size overflow".to_string())
        })?;
    let expected_size = OUTER_HEADER_SIZE
        .checked_add(INNER_HEADER_SIZE)
        .and_then(|value| value.checked_add(nodes_size))
        .and_then(|value| value.checked_add(free_nodes_size))
        .ok_or_else(|| {
            StoreError::InvalidParams("C++ OffsetAllocator state size overflow".to_string())
        })?;
    if bytes.len() != expected_size {
        return Err(StoreError::InvalidParams(format!(
            "C++ OffsetAllocator allocator_state size mismatch: expected {expected_size}, got {}",
            bytes.len()
        )));
    }

    let nodes_start = OUTER_HEADER_SIZE + INNER_HEADER_SIZE;
    let mut nodes = Vec::with_capacity(current_capacity as usize);
    for node_index in 0..current_capacity as usize {
        let node = nodes_start + node_index * NODE_SIZE;
        let references = [
            read_u32_le(bytes, node + 8)?,
            read_u32_le(bytes, node + 12)?,
            read_u32_le(bytes, node + 16)?,
            read_u32_le(bytes, node + 20)?,
        ];
        if references
            .iter()
            .any(|index| *index != u32::MAX && *index >= current_capacity)
        {
            return Err(StoreError::InvalidParams(format!(
                "C++ OffsetAllocator node {node_index} contains an out-of-range reference"
            )));
        }
        let used = bytes[node + 24];
        if used > 1 {
            return Err(StoreError::InvalidParams(format!(
                "C++ OffsetAllocator node {node_index} has an invalid bool encoding"
            )));
        }
        nodes.push((
            read_u32_le(bytes, node)?,
            read_u32_le(bytes, node + 4)?,
            used == 1,
            references[2],
            references[3],
        ));
    }

    let free_nodes_start = nodes_start + nodes_size;
    let mut node_permutation = HashSet::with_capacity(current_capacity as usize);
    let mut active_nodes = HashSet::with_capacity(free_offset as usize);
    for position in 0..current_capacity as usize {
        let node_index = read_u32_le(bytes, free_nodes_start + position * FREE_NODE_SIZE)?;
        if node_index >= current_capacity || !node_permutation.insert(node_index) {
            return Err(StoreError::InvalidParams(
                "C++ OffsetAllocator freeNodes is not a permutation of node indices".to_string(),
            ));
        }
        if position < free_offset as usize {
            active_nodes.insert(node_index);
        }
    }

    let mut active_extents = Vec::with_capacity(active_nodes.len());
    let mut computed_free_storage = 0_u64;
    let mut used_extents = Vec::new();
    for node_index in active_nodes.iter().copied() {
        let (raw_offset, raw_size, used, neighbor_prev, neighbor_next) = nodes[node_index as usize];
        let data_offset = u64::from(raw_offset);
        let data_size = u64::from(raw_size);
        if data_size == 0 {
            return Err(StoreError::InvalidParams(format!(
                "C++ OffsetAllocator active node {node_index} has zero size"
            )));
        }
        let unit_end = data_offset.checked_add(data_size).ok_or_else(|| {
            StoreError::InvalidParams(format!(
                "C++ OffsetAllocator node {node_index} unit extent overflow"
            ))
        })?;
        if unit_end > u64::from(size) {
            return Err(StoreError::InvalidParams(format!(
                "C++ OffsetAllocator node {node_index} exceeds internal size"
            )));
        }
        for neighbor in [neighbor_prev, neighbor_next] {
            if neighbor != u32::MAX && !active_nodes.contains(&neighbor) {
                return Err(StoreError::InvalidParams(format!(
                    "C++ OffsetAllocator node {node_index} references an inactive neighbor"
                )));
            }
        }
        if neighbor_prev != u32::MAX {
            let previous = nodes[neighbor_prev as usize];
            if previous.4 != node_index
                || u64::from(previous.0) + u64::from(previous.1) != data_offset
            {
                return Err(StoreError::InvalidParams(format!(
                    "C++ OffsetAllocator node {node_index} has a broken previous-neighbor link"
                )));
            }
        }
        if neighbor_next != u32::MAX {
            let next = nodes[neighbor_next as usize];
            if next.3 != node_index || unit_end != u64::from(next.0) {
                return Err(StoreError::InvalidParams(format!(
                    "C++ OffsetAllocator node {node_index} has a broken next-neighbor link"
                )));
            }
        }
        active_extents.push((data_offset, data_size));
        if !used {
            computed_free_storage =
                computed_free_storage
                    .checked_add(data_size)
                    .ok_or_else(|| {
                        StoreError::InvalidParams(
                            "C++ OffsetAllocator free storage overflow".to_string(),
                        )
                    })?;
            continue;
        }
        let offset = data_offset
            .checked_shl(multiplier_bits as u32)
            .and_then(|value| base.checked_add(value))
            .ok_or_else(|| {
                StoreError::InvalidParams(format!(
                    "C++ OffsetAllocator node {node_index} offset overflow"
                ))
            })?;
        let allocated_size = data_size
            .checked_shl(multiplier_bits as u32)
            .ok_or_else(|| {
                StoreError::InvalidParams(format!(
                    "C++ OffsetAllocator node {node_index} size overflow"
                ))
            })?;
        let end = offset.checked_add(allocated_size).ok_or_else(|| {
            StoreError::InvalidParams(format!(
                "C++ OffsetAllocator node {node_index} extent overflow"
            ))
        })?;
        if end > capacity {
            return Err(StoreError::InvalidParams(format!(
                "C++ OffsetAllocator node {node_index} exceeds capacity"
            )));
        }
        used_extents.push((offset, allocated_size));
    }
    if computed_free_storage != u64::from(free_storage) {
        return Err(StoreError::InvalidParams(format!(
            "C++ OffsetAllocator free storage mismatch: header={free_storage}, nodes={computed_free_storage}"
        )));
    }
    active_extents.sort_unstable_by_key(|(offset, _)| *offset);
    let mut next_unit = 0_u64;
    for (offset, extent_size) in active_extents {
        if offset != next_unit {
            return Err(StoreError::InvalidParams(
                "C++ OffsetAllocator active nodes do not form a complete partition".to_string(),
            ));
        }
        next_unit = next_unit.checked_add(extent_size).ok_or_else(|| {
            StoreError::InvalidParams("C++ OffsetAllocator active partition overflow".to_string())
        })?;
    }
    if next_unit != u64::from(size) {
        return Err(StoreError::InvalidParams(
            "C++ OffsetAllocator active partition does not cover allocator size".to_string(),
        ));
    }
    if used_extents.len() as u64 != allocated_num {
        return Err(StoreError::InvalidParams(format!(
            "C++ OffsetAllocator allocated_num mismatch: header={allocated_num}, used_nodes={}",
            used_extents.len()
        )));
    }
    used_extents.sort_unstable_by_key(|(offset, _)| *offset);
    for pair in used_extents.windows(2) {
        if pair[0].0 + pair[0].1 > pair[1].0 {
            return Err(StoreError::InvalidParams(
                "C++ OffsetAllocator contains overlapping used extents".to_string(),
            ));
        }
    }
    Ok(CppAllocatorImage {
        capacity,
        allocated_size,
        used_extents,
    })
}

fn read_cpp_offset_record(
    source: &mut std::fs::File,
    offset: u64,
    allocated_size: u64,
    capacity: u64,
    checkpoint_insert_seq: u64,
    default_tenant_id: &str,
) -> StoreResult<Option<CppOffsetRecord>> {
    let mut encoded_header = [0_u8; RECORD_HEADER_SIZE];
    read_exact_at(source, offset, &mut encoded_header)?;
    let Ok(header) = RecordHeader::decode(&encoded_header) else {
        return Ok(None);
    };
    let Ok(record_size) = header.checked_record_size() else {
        return Ok(None);
    };
    if record_size > allocated_size
        || offset
            .checked_add(record_size)
            .is_none_or(|end| end > capacity)
    {
        return Ok(None);
    }
    if header.write_seq >= checkpoint_insert_seq {
        return Ok(None);
    }
    let mut record_bytes = vec![0_u8; record_size as usize];
    read_exact_at(source, offset, &mut record_bytes)?;
    let key_end = RECORD_HEADER_SIZE + header.key_len as usize;
    let value_relative = RecordHeader::value_offset(header.key_len.into()).map_err(|error| {
        StoreError::InvalidParams(format!(
            "invalid C++ OffsetAllocator value offset at {offset}: {}",
            error.0
        ))
    })? as usize;
    let key_bytes = &record_bytes[RECORD_HEADER_SIZE..key_end];
    let value = &record_bytes[value_relative..];
    if header.verify_crc(key_bytes, value).is_err() {
        return Ok(None);
    }
    let source_key = std::str::from_utf8(key_bytes).map_err(|error| {
        StoreError::InvalidParams(format!(
            "C++ OffsetAllocator key at {offset} is not UTF-8: {error}"
        ))
    })?;
    let storage_key = scoped_storage_key(source_key, default_tenant_id)?;
    Ok(Some(CppOffsetRecord {
        source_key: source_key.to_string(),
        storage_key,
        offset,
        record_size,
        value_offset: offset + value_relative as u64,
        value_size: header.value_len.into(),
        write_seq: header.write_seq,
        has_crc: header.has_crc(),
        record_sha256: Sha256::digest(&record_bytes).into(),
    }))
}

fn reread_cpp_offset_value(
    source: &mut std::fs::File,
    record: &CppOffsetRecord,
) -> StoreResult<Vec<u8>> {
    let mut record_bytes = vec![0_u8; record.record_size as usize];
    read_exact_at(source, record.offset, &mut record_bytes)?;
    if <[u8; 32]>::from(Sha256::digest(&record_bytes)) != record.record_sha256 {
        return Err(StoreError::InvalidParams(format!(
            "C++ OffsetAllocator source record changed during migration at offset {}",
            record.offset
        )));
    }
    let relative = (record.value_offset - record.offset) as usize;
    Ok(record_bytes[relative..].to_vec())
}

fn verify_cpp_offset_source(
    data_path: &Path,
    meta_path: &Path,
    data_identity: SourceFileIdentity,
    meta_sha256: [u8; 32],
    records: &[CppOffsetRecord],
) -> StoreResult<()> {
    let current_identity = source_file_identity(&std::fs::metadata(data_path)?);
    if current_identity != data_identity {
        return Err(StoreError::InvalidParams(
            "C++ OffsetAllocator data file identity changed before publish".to_string(),
        ));
    }
    if <[u8; 32]>::from(Sha256::digest(std::fs::read(meta_path)?)) != meta_sha256 {
        return Err(StoreError::InvalidParams(
            "C++ OffsetAllocator metadata changed before publish".to_string(),
        ));
    }
    let mut data = std::fs::File::open(data_path)?;
    for record in records {
        let _ = reread_cpp_offset_value(&mut data, record)?;
    }
    Ok(())
}

fn read_exact_at(file: &mut std::fs::File, offset: u64, buffer: &mut [u8]) -> StoreResult<()> {
    file.seek(SeekFrom::Start(offset))?;
    file.read_exact(buffer)?;
    Ok(())
}

fn read_u32_le(bytes: &[u8], offset: usize) -> StoreResult<u32> {
    let encoded = bytes.get(offset..offset + 4).ok_or_else(|| {
        StoreError::InvalidParams("truncated C++ OffsetAllocator integer".to_string())
    })?;
    Ok(u32::from_le_bytes(encoded.try_into().unwrap()))
}

fn read_u64_le(bytes: &[u8], offset: usize) -> StoreResult<u64> {
    let encoded = bytes.get(offset..offset + 8).ok_or_else(|| {
        StoreError::InvalidParams("truncated C++ OffsetAllocator integer".to_string())
    })?;
    Ok(u64::from_le_bytes(encoded.try_into().unwrap()))
}

fn validate_regular_file(path: &Path, context: &str) -> StoreResult<()> {
    let metadata = std::fs::symlink_metadata(path).map_err(|error| {
        StoreError::InvalidParams(format!(
            "{context} is unavailable ({}): {error}",
            path.display()
        ))
    })?;
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(StoreError::InvalidParams(format!(
            "{context} must be a regular file: {}",
            path.display()
        )));
    }
    Ok(())
}

fn validate_single_component(value: &str, context: &str) -> StoreResult<()> {
    let mut components = Path::new(value).components();
    if !matches!(
        (components.next(), components.next()),
        (Some(std::path::Component::Normal(_)), None)
    ) {
        return Err(StoreError::InvalidParams(format!(
            "{context} must be exactly one normal path component"
        )));
    }
    Ok(())
}

fn reject_overlapping_trees(
    source: &Path,
    target_root: &Path,
    target_fsdir: &str,
) -> StoreResult<()> {
    let canonical_source = std::fs::canonicalize(source)?;
    let canonical_target_root = std::fs::canonicalize(target_root)?;
    let canonical_target = canonical_target_root.join(target_fsdir);
    if canonical_target.starts_with(&canonical_source)
        || canonical_source.starts_with(&canonical_target)
    {
        return Err(StoreError::InvalidParams(format!(
            "migration source and target must not overlap: source={}, target={}",
            canonical_source.display(),
            canonical_target.display()
        )));
    }
    Ok(())
}

#[cfg(target_os = "linux")]
fn rename_directory_noreplace(source: &Path, target: &Path) -> StoreResult<()> {
    let source = CString::new(source.as_os_str().as_bytes())
        .map_err(|_| StoreError::InvalidParams("migration source path contains NUL".to_string()))?;
    let target = CString::new(target.as_os_str().as_bytes())
        .map_err(|_| StoreError::InvalidParams("migration target path contains NUL".to_string()))?;
    // SAFETY: both C strings are NUL-terminated and remain alive for the call.
    let result = unsafe {
        libc::renameat2(
            libc::AT_FDCWD,
            source.as_ptr(),
            libc::AT_FDCWD,
            target.as_ptr(),
            libc::RENAME_NOREPLACE,
        )
    };
    if result == 0 {
        Ok(())
    } else {
        Err(std::io::Error::last_os_error().into())
    }
}

#[cfg(target_os = "macos")]
fn rename_directory_noreplace(source: &Path, target: &Path) -> StoreResult<()> {
    let source = CString::new(source.as_os_str().as_bytes())
        .map_err(|_| StoreError::InvalidParams("migration source path contains NUL".to_string()))?;
    let target = CString::new(target.as_os_str().as_bytes())
        .map_err(|_| StoreError::InvalidParams("migration target path contains NUL".to_string()))?;
    // SAFETY: both C strings are NUL-terminated and remain alive for the call.
    let result = unsafe { libc::renamex_np(source.as_ptr(), target.as_ptr(), libc::RENAME_EXCL) };
    if result == 0 {
        Ok(())
    } else {
        Err(std::io::Error::last_os_error().into())
    }
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
fn rename_directory_noreplace(_source: &Path, _target: &Path) -> StoreResult<()> {
    Err(StoreError::InvalidParams(
        "atomic no-replace FilePerKey migration publish is unsupported on this platform"
            .to_string(),
    ))
}

fn sync_directory_tree(root: &Path) -> StoreResult<()> {
    let mut directories = vec![root.to_path_buf()];
    collect_directories_recursive(root, &mut directories)?;
    directories.sort_by_key(|path| std::cmp::Reverse(path.components().count()));
    for directory in directories {
        sync_directory(&directory)?;
    }
    Ok(())
}

fn collect_directories_recursive(dir: &Path, directories: &mut Vec<PathBuf>) -> StoreResult<()> {
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        let path = entry.path();
        if file_type.is_symlink() {
            return Err(StoreError::InvalidParams(format!(
                "FilePerKey migration staging contains a symbolic link: {}",
                path.display()
            )));
        }
        if file_type.is_dir() {
            directories.push(path.clone());
            collect_directories_recursive(&path, directories)?;
        } else if !file_type.is_file() {
            return Err(StoreError::InvalidParams(format!(
                "FilePerKey migration staging contains a non-regular entry: {}",
                path.display()
            )));
        }
    }
    Ok(())
}

fn validate_default_tenant(tenant_id: &str) -> StoreResult<()> {
    validate_tenant_id(tenant_id, "default migration tenant")
}

fn validate_tenant_id(tenant_id: &str, context: &str) -> StoreResult<()> {
    if tenant_id.is_empty()
        || tenant_id.starts_with('_')
        || tenant_id
            .as_bytes()
            .iter()
            .any(|byte| *byte < 0x20 || *byte == 0x7f)
    {
        return Err(StoreError::InvalidParams(format!(
            "{context} is invalid: tenant must be non-empty, must not start with '_', and \
             must not contain ASCII control bytes"
        )));
    }
    Ok(())
}

fn scoped_storage_key(source_key: &str, default_tenant_id: &str) -> StoreResult<String> {
    let (tenant_id, user_key) = match source_key.split_once('\0') {
        Some((tenant_id, user_key)) if !tenant_id.is_empty() => (tenant_id, user_key),
        Some(_) => {
            return Err(StoreError::InvalidParams(format!(
                "invalid tenant-scoped C++ storage key: {source_key:?}"
            )));
        }
        None => (default_tenant_id, source_key),
    };
    validate_tenant_id(tenant_id, "C++ storage source tenant")?;
    if user_key.is_empty() {
        return Err(StoreError::InvalidParams(
            "C++ storage record has an empty user key".to_string(),
        ));
    }
    Ok(local_storage_key(tenant_id, user_key))
}

fn collect_source_files(root: &Path) -> StoreResult<Vec<PathBuf>> {
    let mut files = Vec::new();
    collect_source_files_recursive(root, &mut files)?;
    files.sort_by(|left, right| {
        let timestamp = |path: &Path| {
            std::fs::metadata(path)
                .and_then(|metadata| metadata.created().or_else(|_| metadata.modified()))
                .unwrap_or(UNIX_EPOCH)
        };
        timestamp(left)
            .cmp(&timestamp(right))
            .then_with(|| left.cmp(right))
    });
    Ok(files)
}

fn collect_source_files_recursive(dir: &Path, files: &mut Vec<PathBuf>) -> StoreResult<()> {
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        let path = entry.path();
        if file_type.is_symlink() {
            return Err(StoreError::InvalidParams(format!(
                "FilePerKey migration refuses symbolic links: {}",
                path.display()
            )));
        }
        if file_type.is_dir() {
            collect_source_files_recursive(&path, files)?;
        } else if file_type.is_file() {
            files.push(path);
        } else {
            return Err(StoreError::InvalidParams(format!(
                "FilePerKey migration source contains a non-regular entry: {}",
                path.display()
            )));
        }
    }
    Ok(())
}
