//! # gRPC Service Trait Implementation
//! ## gRPC 服务 trait 实现 / Tonic MasterService trait impl
//!
//! 本模块将 `MasterService` protobuf trait（由 tonic/build.rs 自动生成）实现到
//! `MasterServiceImpl` 上。每个 RPC 方法都委托给对应的 `*_impl` 方法，
//! 后者定义在各自的功能域文件中：
//!
//! This module implements the `MasterService` protobuf trait (auto-generated by tonic/build.rs)
//! on `MasterServiceImpl`. Each RPC method delegates to the corresponding `*_impl` method
//! defined in the respective functional domain file:
//!
//! | RPC 方法 | 委托到 / Delegates to | 功能域 / Domain |
//! |----------|----------------------|----------------|
//! | `ping`, `mount_segment`, `unmount_segment`, ... | `grpc_cluster.rs` | 集群管理 / Cluster |
//! | `put_start`, `put_end`, `get_replica_list`, ... | `grpc_objects.rs` | 对象 CRUD / Objects |
//! | `copy_start`, `copy_end`, `move_start`, ... | `grpc_replication.rs` | 副本复制 / Replication |
//! | `create_copy_task`, `fetch_tasks`, ... | `grpc_tasks.rs` | 任务队列 / Tasks |
//! | `batch_*` | `grpc_batches.rs` | 批量操作 / Batches |
//!
//! 这种间接层使代码按功能域组织，同时保持 protobuf trait 实现在一个文件中。
//! The indirection layer keeps code organized by functional domain while
//! maintaining the protobuf trait impl in a single file.

use super::*;

#[tonic::async_trait]
impl MasterService for MasterServiceImpl {
    // ===== Cluster Management (grpc_cluster.rs) =====
    // ===== 集群管理 =====

    async fn ping(
        &self,
        request: Request<proto::PingRequest>,
    ) -> Result<Response<proto::PingResponse>, Status> {
        MasterServiceImpl::ping_impl(self, request).await
    }

    async fn mount_segment(
        &self,
        request: Request<proto::MountSegmentRequest>,
    ) -> Result<Response<proto::MountSegmentResponse>, Status> {
        MasterServiceImpl::mount_segment_impl(self, request).await
    }

    async fn mount_no_f_segment(
        &self,
        request: Request<proto::MountNoFSegmentRequest>,
    ) -> Result<Response<proto::MountNoFSegmentResponse>, Status> {
        MasterServiceImpl::mount_nof_segment_impl(self, request).await
    }

    async fn unmount_segment(
        &self,
        request: Request<proto::UnmountSegmentRequest>,
    ) -> Result<Response<proto::UnmountSegmentResponse>, Status> {
        MasterServiceImpl::unmount_segment_impl(self, request).await
    }

    async fn unmount_no_f_segment(
        &self,
        request: Request<proto::UnmountNoFSegmentRequest>,
    ) -> Result<Response<proto::UnmountNoFSegmentResponse>, Status> {
        MasterServiceImpl::unmount_nof_segment_impl(self, request).await
    }

    async fn graceful_unmount_segment(
        &self,
        request: Request<proto::GracefulUnmountSegmentRequest>,
    ) -> Result<Response<proto::GracefulUnmountSegmentResponse>, Status> {
        MasterServiceImpl::graceful_unmount_segment_impl(self, request).await
    }

    async fn re_mount_segment(
        &self,
        request: Request<proto::ReMountSegmentRequest>,
    ) -> Result<Response<proto::ReMountSegmentResponse>, Status> {
        MasterServiceImpl::re_mount_segment_impl(self, request).await
    }

    async fn re_mount_no_f_segment(
        &self,
        request: Request<proto::ReMountNoFSegmentRequest>,
    ) -> Result<Response<proto::ReMountNoFSegmentResponse>, Status> {
        MasterServiceImpl::re_mount_nof_segment_impl(self, request).await
    }

    async fn mount_local_disk_segment(
        &self,
        request: Request<proto::MountLocalDiskSegmentRequest>,
    ) -> Result<Response<proto::MountLocalDiskSegmentResponse>, Status> {
        MasterServiceImpl::mount_local_disk_segment_impl(self, request).await
    }

    async fn offload_object_heartbeat(
        &self,
        request: Request<proto::OffloadObjectHeartbeatRequest>,
    ) -> Result<Response<proto::OffloadObjectHeartbeatResponse>, Status> {
        MasterServiceImpl::offload_object_heartbeat_impl(self, request).await
    }

    async fn report_ssd_capacity(
        &self,
        request: Request<proto::ReportSsdCapacityRequest>,
    ) -> Result<Response<proto::ReportSsdCapacityResponse>, Status> {
        MasterServiceImpl::report_ssd_capacity_impl(self, request).await
    }

    async fn notify_offload_success(
        &self,
        request: Request<proto::NotifyOffloadSuccessRequest>,
    ) -> Result<Response<proto::NotifyOffloadSuccessResponse>, Status> {
        MasterServiceImpl::notify_offload_success_impl(self, request).await
    }

    async fn promotion_object_heartbeat(
        &self,
        request: Request<proto::PromotionObjectHeartbeatRequest>,
    ) -> Result<Response<proto::PromotionObjectHeartbeatResponse>, Status> {
        MasterServiceImpl::promotion_object_heartbeat_impl(self, request).await
    }

    async fn promotion_alloc_start(
        &self,
        request: Request<proto::PromotionAllocStartRequest>,
    ) -> Result<Response<proto::PromotionAllocStartResponse>, Status> {
        MasterServiceImpl::promotion_alloc_start_impl(self, request).await
    }

    async fn notify_promotion_success(
        &self,
        request: Request<proto::NotifyPromotionSuccessRequest>,
    ) -> Result<Response<proto::NotifyPromotionSuccessResponse>, Status> {
        MasterServiceImpl::notify_promotion_success_impl(self, request).await
    }

    async fn notify_promotion_failure(
        &self,
        request: Request<proto::NotifyPromotionFailureRequest>,
    ) -> Result<Response<proto::NotifyPromotionFailureResponse>, Status> {
        MasterServiceImpl::notify_promotion_failure_impl(self, request).await
    }

    // ===== Object CRUD (grpc_objects.rs) =====
    // ===== 对象增删改查 =====

    async fn exist_key(
        &self,
        request: Request<proto::ExistKeyRequest>,
    ) -> Result<Response<proto::ExistKeyResponse>, Status> {
        MasterServiceImpl::exist_key_impl(self, request).await
    }

    async fn get_all_keys(
        &self,
        request: Request<proto::GetAllKeysRequest>,
    ) -> Result<Response<proto::GetAllKeysResponse>, Status> {
        MasterServiceImpl::get_all_keys_impl(self, request).await
    }

    async fn get_all_segments(
        &self,
        request: Request<proto::GetAllSegmentsRequest>,
    ) -> Result<Response<proto::GetAllSegmentsResponse>, Status> {
        MasterServiceImpl::get_all_segments_impl(self, request).await
    }

    async fn get_all_no_f_segments(
        &self,
        request: Request<proto::GetAllNoFSegmentsRequest>,
    ) -> Result<Response<proto::GetAllNoFSegmentsResponse>, Status> {
        MasterServiceImpl::get_all_nof_segments_impl(self, request).await
    }

    async fn get_no_f_segments_by_name(
        &self,
        request: Request<proto::GetNoFSegmentsByNameRequest>,
    ) -> Result<Response<proto::GetNoFSegmentsByNameResponse>, Status> {
        MasterServiceImpl::get_nof_segments_by_name_impl(self, request).await
    }

    async fn service_ready(
        &self,
        request: Request<proto::ServiceReadyRequest>,
    ) -> Result<Response<proto::ServiceReadyResponse>, Status> {
        MasterServiceImpl::service_ready_impl(self, request).await
    }

    async fn get_all_keys_for_admin(
        &self,
        request: Request<proto::GetAllKeysForAdminRequest>,
    ) -> Result<Response<proto::GetAllKeysForAdminResponse>, Status> {
        MasterServiceImpl::get_all_keys_for_admin_impl(self, request).await
    }

    async fn get_all_segments_for_admin(
        &self,
        request: Request<proto::GetAllSegmentsForAdminRequest>,
    ) -> Result<Response<proto::GetAllSegmentsForAdminResponse>, Status> {
        MasterServiceImpl::get_all_segments_for_admin_impl(self, request).await
    }

    async fn query_segment_for_admin(
        &self,
        request: Request<proto::QuerySegmentsRequest>,
    ) -> Result<Response<proto::QuerySegmentsResponse>, Status> {
        MasterServiceImpl::query_segment_for_admin_impl(self, request).await
    }

    async fn calc_cache_stats(
        &self,
        request: Request<proto::CalcCacheStatsRequest>,
    ) -> Result<Response<proto::CalcCacheStatsResponse>, Status> {
        MasterServiceImpl::calc_cache_stats_impl(self, request).await
    }

    async fn put_start(
        &self,
        request: Request<proto::PutStartRequest>,
    ) -> Result<Response<proto::PutStartResponse>, Status> {
        MasterServiceImpl::put_start_impl(self, request).await
    }

    async fn put_end(
        &self,
        request: Request<proto::PutEndRequest>,
    ) -> Result<Response<proto::PutEndResponse>, Status> {
        MasterServiceImpl::put_end_impl(self, request).await
    }

    async fn put_revoke(
        &self,
        request: Request<proto::PutRevokeRequest>,
    ) -> Result<Response<proto::PutRevokeResponse>, Status> {
        MasterServiceImpl::put_revoke_impl(self, request).await
    }

    async fn add_replica(
        &self,
        request: Request<proto::AddReplicaRequest>,
    ) -> Result<Response<proto::AddReplicaResponse>, Status> {
        MasterServiceImpl::add_replica_impl(self, request).await
    }

    async fn get_replica_list(
        &self,
        request: Request<proto::GetReplicaListRequest>,
    ) -> Result<Response<proto::GetReplicaListResponse>, Status> {
        MasterServiceImpl::get_replica_list_impl(self, request).await
    }

    async fn get_replica_list_by_regex(
        &self,
        request: Request<proto::GetReplicaListByRegexRequest>,
    ) -> Result<Response<proto::GetReplicaListByRegexResponse>, Status> {
        MasterServiceImpl::get_replica_list_by_regex_impl(self, request).await
    }

    async fn remove(
        &self,
        request: Request<proto::RemoveRequest>,
    ) -> Result<Response<proto::RemoveResponse>, Status> {
        MasterServiceImpl::remove_impl(self, request).await
    }

    async fn remove_by_regex(
        &self,
        request: Request<proto::RemoveByRegexRequest>,
    ) -> Result<Response<proto::RemoveByRegexResponse>, Status> {
        MasterServiceImpl::remove_by_regex_impl(self, request).await
    }

    async fn remove_all(
        &self,
        request: Request<proto::RemoveAllRequest>,
    ) -> Result<Response<proto::RemoveAllResponse>, Status> {
        MasterServiceImpl::remove_all_impl(self, request).await
    }

    // ===== Batch Operations (grpc_batches.rs) =====
    // ===== 批量操作 =====

    async fn batch_exist_key(
        &self,
        request: Request<proto::BatchExistKeyRequest>,
    ) -> Result<Response<proto::BatchExistKeyResponse>, Status> {
        MasterServiceImpl::batch_exist_key_impl(self, request).await
    }

    async fn batch_query_ip(
        &self,
        request: Request<proto::BatchQueryIpRequest>,
    ) -> Result<Response<proto::BatchQueryIpResponse>, Status> {
        MasterServiceImpl::batch_query_ip_impl(self, request).await
    }

    async fn batch_replica_clear(
        &self,
        request: Request<proto::BatchReplicaClearRequest>,
    ) -> Result<Response<proto::BatchReplicaClearResponse>, Status> {
        MasterServiceImpl::batch_replica_clear_impl(self, request).await
    }

    async fn query_by_regex(
        &self,
        request: Request<proto::QueryByRegexRequest>,
    ) -> Result<Response<proto::QueryByRegexResponse>, Status> {
        MasterServiceImpl::query_by_regex_impl(self, request).await
    }

    async fn query_segments(
        &self,
        request: Request<proto::QuerySegmentsRequest>,
    ) -> Result<Response<proto::QuerySegmentsResponse>, Status> {
        MasterServiceImpl::query_segments_impl(self, request).await
    }

    async fn query_ip(
        &self,
        request: Request<proto::QueryIpRequest>,
    ) -> Result<Response<proto::QueryIpResponse>, Status> {
        MasterServiceImpl::query_ip_impl(self, request).await
    }

    async fn get_storage_config(
        &self,
        request: Request<proto::GetStorageConfigRequest>,
    ) -> Result<Response<proto::GetStorageConfigResponse>, Status> {
        MasterServiceImpl::get_storage_config_impl(self, request).await
    }

    async fn upsert(
        &self,
        request: Request<proto::UpsertRequest>,
    ) -> Result<Response<proto::UpsertResponse>, Status> {
        MasterServiceImpl::upsert_impl(self, request).await
    }

    async fn batch_upsert_start(
        &self,
        request: Request<proto::BatchUpsertStartRequest>,
    ) -> Result<Response<proto::BatchUpsertStartResponse>, Status> {
        MasterServiceImpl::batch_upsert_start_impl(self, request).await
    }

    // ===== Replica Replication (grpc_replication.rs) =====
    // ===== 副本复制/迁移 =====

    async fn copy_start(
        &self,
        request: Request<proto::CopyStartRequest>,
    ) -> Result<Response<proto::CopyStartResponse>, Status> {
        MasterServiceImpl::copy_start_impl(self, request).await
    }

    async fn copy_end(
        &self,
        request: Request<proto::CopyEndRequest>,
    ) -> Result<Response<proto::CopyEndResponse>, Status> {
        MasterServiceImpl::copy_end_impl(self, request).await
    }

    async fn copy_revoke(
        &self,
        request: Request<proto::CopyRevokeRequest>,
    ) -> Result<Response<proto::CopyRevokeResponse>, Status> {
        MasterServiceImpl::copy_revoke_impl(self, request).await
    }

    async fn move_start(
        &self,
        request: Request<proto::MoveStartRequest>,
    ) -> Result<Response<proto::MoveStartResponse>, Status> {
        MasterServiceImpl::move_start_impl(self, request).await
    }

    async fn move_end(
        &self,
        request: Request<proto::MoveEndRequest>,
    ) -> Result<Response<proto::MoveEndResponse>, Status> {
        MasterServiceImpl::move_end_impl(self, request).await
    }

    async fn move_revoke(
        &self,
        request: Request<proto::MoveRevokeRequest>,
    ) -> Result<Response<proto::MoveRevokeResponse>, Status> {
        MasterServiceImpl::move_revoke_impl(self, request).await
    }

    // ===== Task Queue (grpc_tasks.rs) =====
    // ===== 任务队列 =====

    async fn create_copy_task(
        &self,
        request: Request<proto::CreateCopyTaskRequest>,
    ) -> Result<Response<proto::CreateCopyTaskResponse>, Status> {
        MasterServiceImpl::create_copy_task_impl(self, request).await
    }

    async fn create_move_task(
        &self,
        request: Request<proto::CreateMoveTaskRequest>,
    ) -> Result<Response<proto::CreateMoveTaskResponse>, Status> {
        MasterServiceImpl::create_move_task_impl(self, request).await
    }

    async fn query_task(
        &self,
        request: Request<proto::QueryTaskRequest>,
    ) -> Result<Response<proto::QueryTaskResponse>, Status> {
        MasterServiceImpl::query_task_impl(self, request).await
    }

    async fn fetch_tasks(
        &self,
        request: Request<proto::FetchTasksRequest>,
    ) -> Result<Response<proto::FetchTasksResponse>, Status> {
        MasterServiceImpl::fetch_tasks_impl(self, request).await
    }

    async fn mark_task_to_complete(
        &self,
        request: Request<proto::MarkTaskToCompleteRequest>,
    ) -> Result<Response<proto::MarkTaskToCompleteResponse>, Status> {
        MasterServiceImpl::mark_task_to_complete_impl(self, request).await
    }

    // ===== More Batch Operations (grpc_batches.rs) =====
    // ===== 更多批量操作 =====

    async fn batch_put_end(
        &self,
        request: Request<proto::BatchPutEndRequest>,
    ) -> Result<Response<proto::BatchPutEndResponse>, Status> {
        MasterServiceImpl::batch_put_end_impl(self, request).await
    }

    async fn batch_put_revoke(
        &self,
        request: Request<proto::BatchPutRevokeRequest>,
    ) -> Result<Response<proto::BatchPutRevokeResponse>, Status> {
        MasterServiceImpl::batch_put_revoke_impl(self, request).await
    }

    async fn batch_remove(
        &self,
        request: Request<proto::BatchRemoveRequest>,
    ) -> Result<Response<proto::BatchRemoveResponse>, Status> {
        MasterServiceImpl::batch_remove_impl(self, request).await
    }

    async fn batch_upsert_end(
        &self,
        request: Request<proto::BatchUpsertEndRequest>,
    ) -> Result<Response<proto::BatchUpsertEndResponse>, Status> {
        MasterServiceImpl::batch_upsert_end_impl(self, request).await
    }

    async fn batch_upsert_revoke(
        &self,
        request: Request<proto::BatchUpsertRevokeRequest>,
    ) -> Result<Response<proto::BatchUpsertRevokeResponse>, Status> {
        MasterServiceImpl::batch_upsert_revoke_impl(self, request).await
    }

    async fn batch_put_start(
        &self,
        request: Request<proto::BatchPutStartRequest>,
    ) -> Result<Response<proto::BatchPutStartResponse>, Status> {
        MasterServiceImpl::batch_put_start_impl(self, request).await
    }

    async fn evict_disk_replica(
        &self,
        request: Request<proto::EvictDiskReplicaRequest>,
    ) -> Result<Response<proto::EvictDiskReplicaResponse>, Status> {
        MasterServiceImpl::evict_disk_replica_impl(self, request).await
    }

    async fn batch_evict_disk_replica(
        &self,
        request: Request<proto::BatchEvictDiskReplicaRequest>,
    ) -> Result<Response<proto::BatchEvictDiskReplicaResponse>, Status> {
        MasterServiceImpl::batch_evict_disk_replica_impl(self, request).await
    }

    // ===== Segment Status (grpc_cluster.rs) =====
    // ===== Segment 状态查询 =====

    async fn query_segment_status(
        &self,
        request: Request<proto::QuerySegmentStatusRequest>,
    ) -> Result<Response<proto::QuerySegmentStatusResponse>, Status> {
        MasterServiceImpl::query_segment_status_impl(self, request).await
    }

    async fn query_segment_status_by_id(
        &self,
        request: Request<proto::QuerySegmentStatusByIdRequest>,
    ) -> Result<Response<proto::QuerySegmentStatusByIdResponse>, Status> {
        MasterServiceImpl::query_segment_status_by_id_impl(self, request).await
    }

    async fn create_drain_job(
        &self,
        request: Request<proto::CreateDrainJobRequest>,
    ) -> Result<Response<proto::CreateDrainJobResponse>, Status> {
        MasterServiceImpl::create_drain_job_impl(self, request).await
    }

    async fn query_drain_job(
        &self,
        request: Request<proto::QueryDrainJobRequest>,
    ) -> Result<Response<proto::QueryDrainJobResponse>, Status> {
        MasterServiceImpl::query_drain_job_impl(self, request).await
    }

    async fn cancel_drain_job(
        &self,
        request: Request<proto::CancelDrainJobRequest>,
    ) -> Result<Response<proto::CancelDrainJobResponse>, Status> {
        MasterServiceImpl::cancel_drain_job_impl(self, request).await
    }

    async fn get_fsdir(
        &self,
        request: Request<proto::GetFsdirRequest>,
    ) -> Result<Response<proto::GetFsdirResponse>, Status> {
        MasterServiceImpl::get_fsdir_impl(self, request).await
    }

    // ===== Remote Pull Coordination (grpc_cluster.rs) =====
    // ===== 远端回源协调 =====

    async fn acquire_remote_pull(
        &self,
        request: Request<proto::AcquireRemotePullRequest>,
    ) -> Result<Response<proto::AcquireRemotePullResponse>, Status> {
        MasterServiceImpl::acquire_remote_pull_impl(self, request).await
    }

    async fn complete_remote_pull(
        &self,
        request: Request<proto::CompleteRemotePullRequest>,
    ) -> Result<Response<proto::CompleteRemotePullResponse>, Status> {
        MasterServiceImpl::complete_remote_pull_impl(self, request).await
    }

    async fn release_remote_pull(
        &self,
        request: Request<proto::ReleaseRemotePullRequest>,
    ) -> Result<Response<proto::ReleaseRemotePullResponse>, Status> {
        MasterServiceImpl::release_remote_pull_impl(self, request).await
    }
}
